# One pod: one initContainer + one container
# Each asking for shared access to a single GPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: npu-test6

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: npu-test6
  name: single-npu
spec:
  spec:
    devices:
      requests:
      - name: npu
        exactly:
          deviceClassName: npu.huawei.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: npu-test6
  name: pod0
spec:
  initContainers:
  - name: init0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export"]
    resources:
      claims:
      - name: shared-npu
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-npu
  resourceClaims:
  - name: shared-npu
    resourceClaimTemplateName: single-npu
