// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profiling.proto

package profiling

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfilingClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilingClientInfo) Reset()         { *m = ProfilingClientInfo{} }
func (m *ProfilingClientInfo) String() string { return proto.CompactTextString(m) }
func (*ProfilingClientInfo) ProtoMessage()    {}
func (*ProfilingClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{0}
}

func (m *ProfilingClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilingClientInfo.Unmarshal(m, b)
}
func (m *ProfilingClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilingClientInfo.Marshal(b, m, deterministic)
}
func (m *ProfilingClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilingClientInfo.Merge(m, src)
}
func (m *ProfilingClientInfo) XXX_Size() int {
	return xxx_messageInfo_ProfilingClientInfo.Size(m)
}
func (m *ProfilingClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilingClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilingClientInfo proto.InternalMessageInfo

func (m *ProfilingClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProfilingClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ProfilingSwitch struct {
	CommunicationOperator string   `protobuf:"bytes,1,opt,name=CommunicationOperator,proto3" json:"CommunicationOperator,omitempty"`
	Step                  string   `protobuf:"bytes,2,opt,name=Step,proto3" json:"Step,omitempty"`
	SaveCheckpoint        string   `protobuf:"bytes,3,opt,name=SaveCheckpoint,proto3" json:"SaveCheckpoint,omitempty"`
	FP                    string   `protobuf:"bytes,4,opt,name=FP,proto3" json:"FP,omitempty"`
	DataLoader            string   `protobuf:"bytes,5,opt,name=DataLoader,proto3" json:"DataLoader,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ProfilingSwitch) Reset()         { *m = ProfilingSwitch{} }
func (m *ProfilingSwitch) String() string { return proto.CompactTextString(m) }
func (*ProfilingSwitch) ProtoMessage()    {}
func (*ProfilingSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{1}
}

func (m *ProfilingSwitch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilingSwitch.Unmarshal(m, b)
}
func (m *ProfilingSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilingSwitch.Marshal(b, m, deterministic)
}
func (m *ProfilingSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilingSwitch.Merge(m, src)
}
func (m *ProfilingSwitch) XXX_Size() int {
	return xxx_messageInfo_ProfilingSwitch.Size(m)
}
func (m *ProfilingSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilingSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilingSwitch proto.InternalMessageInfo

func (m *ProfilingSwitch) GetCommunicationOperator() string {
	if m != nil {
		return m.CommunicationOperator
	}
	return ""
}

func (m *ProfilingSwitch) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *ProfilingSwitch) GetSaveCheckpoint() string {
	if m != nil {
		return m.SaveCheckpoint
	}
	return ""
}

func (m *ProfilingSwitch) GetFP() string {
	if m != nil {
		return m.FP
	}
	return ""
}

func (m *ProfilingSwitch) GetDataLoader() string {
	if m != nil {
		return m.DataLoader
	}
	return ""
}

type DataStatusReq struct {
	JobNsName            string   `protobuf:"bytes,1,opt,name=jobNsName,proto3" json:"jobNsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataStatusReq) Reset()         { *m = DataStatusReq{} }
func (m *DataStatusReq) String() string { return proto.CompactTextString(m) }
func (*DataStatusReq) ProtoMessage()    {}
func (*DataStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{2}
}

func (m *DataStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataStatusReq.Unmarshal(m, b)
}
func (m *DataStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataStatusReq.Marshal(b, m, deterministic)
}
func (m *DataStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataStatusReq.Merge(m, src)
}
func (m *DataStatusReq) XXX_Size() int {
	return xxx_messageInfo_DataStatusReq.Size(m)
}
func (m *DataStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DataStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_DataStatusReq proto.InternalMessageInfo

func (m *DataStatusReq) GetJobNsName() string {
	if m != nil {
		return m.JobNsName
	}
	return ""
}

type DataStatusRes struct {
	Message              string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ProfilingSwitch      *ProfilingSwitch `protobuf:"bytes,2,opt,name=profilingSwitch,proto3" json:"profilingSwitch,omitempty"`
	Code                 int32            `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DataStatusRes) Reset()         { *m = DataStatusRes{} }
func (m *DataStatusRes) String() string { return proto.CompactTextString(m) }
func (*DataStatusRes) ProtoMessage()    {}
func (*DataStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{3}
}

func (m *DataStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataStatusRes.Unmarshal(m, b)
}
func (m *DataStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataStatusRes.Marshal(b, m, deterministic)
}
func (m *DataStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataStatusRes.Merge(m, src)
}
func (m *DataStatusRes) XXX_Size() int {
	return xxx_messageInfo_DataStatusRes.Size(m)
}
func (m *DataStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DataStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_DataStatusRes proto.InternalMessageInfo

func (m *DataStatusRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataStatusRes) GetProfilingSwitch() *ProfilingSwitch {
	if m != nil {
		return m.ProfilingSwitch
	}
	return nil
}

func (m *DataStatusRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type DataTypeReq struct {
	JobNsName            string           `protobuf:"bytes,1,opt,name=jobNsName,proto3" json:"jobNsName,omitempty"`
	ProfilingSwitch      *ProfilingSwitch `protobuf:"bytes,2,opt,name=profilingSwitch,proto3" json:"profilingSwitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DataTypeReq) Reset()         { *m = DataTypeReq{} }
func (m *DataTypeReq) String() string { return proto.CompactTextString(m) }
func (*DataTypeReq) ProtoMessage()    {}
func (*DataTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{4}
}

func (m *DataTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTypeReq.Unmarshal(m, b)
}
func (m *DataTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTypeReq.Marshal(b, m, deterministic)
}
func (m *DataTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTypeReq.Merge(m, src)
}
func (m *DataTypeReq) XXX_Size() int {
	return xxx_messageInfo_DataTypeReq.Size(m)
}
func (m *DataTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DataTypeReq proto.InternalMessageInfo

func (m *DataTypeReq) GetJobNsName() string {
	if m != nil {
		return m.JobNsName
	}
	return ""
}

func (m *DataTypeReq) GetProfilingSwitch() *ProfilingSwitch {
	if m != nil {
		return m.ProfilingSwitch
	}
	return nil
}

type DataTypeRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTypeRes) Reset()         { *m = DataTypeRes{} }
func (m *DataTypeRes) String() string { return proto.CompactTextString(m) }
func (*DataTypeRes) ProtoMessage()    {}
func (*DataTypeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca702880ad38c8b, []int{5}
}

func (m *DataTypeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTypeRes.Unmarshal(m, b)
}
func (m *DataTypeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTypeRes.Marshal(b, m, deterministic)
}
func (m *DataTypeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTypeRes.Merge(m, src)
}
func (m *DataTypeRes) XXX_Size() int {
	return xxx_messageInfo_DataTypeRes.Size(m)
}
func (m *DataTypeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTypeRes.DiscardUnknown(m)
}

var xxx_messageInfo_DataTypeRes proto.InternalMessageInfo

func (m *DataTypeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataTypeRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*ProfilingClientInfo)(nil), "ProfilingClientInfo")
	proto.RegisterType((*ProfilingSwitch)(nil), "ProfilingSwitch")
	proto.RegisterType((*DataStatusReq)(nil), "DataStatusReq")
	proto.RegisterType((*DataStatusRes)(nil), "DataStatusRes")
	proto.RegisterType((*DataTypeReq)(nil), "DataTypeReq")
	proto.RegisterType((*DataTypeRes)(nil), "DataTypeRes")
}

func init() {
	proto.RegisterFile("profiling.proto", fileDescriptor_7ca702880ad38c8b)
}

var fileDescriptor_7ca702880ad38c8b = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x95, 0x5d, 0x68, 0xc5, 0x50, 0xa0, 0xdd, 0x52, 0xc9, 0x42, 0x6d, 0x55, 0xf9, 0x50, 0xf5,
	0x12, 0x2b, 0x22, 0x39, 0x85, 0x48, 0x91, 0x20, 0x22, 0x42, 0x4a, 0x08, 0xb2, 0x39, 0xe5, 0xb6,
	0xb6, 0x17, 0xb3, 0x04, 0xef, 0x3a, 0xbb, 0x4b, 0x22, 0xbe, 0x2b, 0x7f, 0x92, 0x2f, 0x8a, 0xbc,
	0x60, 0x30, 0x0e, 0x49, 0x0e, 0xb9, 0xcd, 0x7b, 0x33, 0xfb, 0x66, 0xde, 0x03, 0x43, 0x23, 0x11,
	0x7c, 0x42, 0xe7, 0x94, 0x45, 0x4e, 0x22, 0xb8, 0xe2, 0xf6, 0x19, 0xfc, 0x18, 0x65, 0x54, 0x6f,
	0x4e, 0x09, 0x53, 0x03, 0x36, 0xe1, 0xa8, 0x09, 0xe5, 0x19, 0xf7, 0x07, 0xa1, 0x65, 0xfc, 0x35,
	0xfe, 0x57, 0xdc, 0x15, 0x40, 0x08, 0x4a, 0x82, 0xcf, 0x89, 0x65, 0x6a, 0x52, 0xd7, 0xf6, 0xa3,
	0x01, 0x8d, 0x8d, 0x82, 0xf7, 0x40, 0x55, 0x30, 0x45, 0xc7, 0xf0, 0xb3, 0xc7, 0xe3, 0x78, 0xc1,
	0x68, 0x80, 0x15, 0xe5, 0xec, 0x3a, 0x21, 0x02, 0x2b, 0x2e, 0xd6, 0x6a, 0xfb, 0x9b, 0xa9, 0xba,
	0xa7, 0x48, 0x92, 0xa9, 0xa7, 0x35, 0xfa, 0x07, 0x75, 0x0f, 0xdf, 0x93, 0xde, 0x94, 0x04, 0xb7,
	0x09, 0xa7, 0x4c, 0x59, 0x9f, 0x74, 0xb7, 0xc0, 0xa2, 0x3a, 0x98, 0xfd, 0x91, 0x55, 0xd2, 0x3d,
	0xb3, 0x3f, 0x42, 0x7f, 0x00, 0xce, 0xb1, 0xc2, 0x97, 0x1c, 0x87, 0x44, 0x58, 0x65, 0xcd, 0xe7,
	0x18, 0xfb, 0x00, 0x6a, 0x29, 0xf2, 0x14, 0x56, 0x0b, 0xe9, 0x92, 0x3b, 0xf4, 0x0b, 0x2a, 0x33,
	0xee, 0x0f, 0xe5, 0x10, 0xc7, 0x64, 0x7d, 0xe6, 0x96, 0xb0, 0x97, 0xbb, 0xe3, 0x12, 0x59, 0xf0,
	0x25, 0x26, 0x52, 0xe2, 0x28, 0x1b, 0xce, 0x20, 0x3a, 0xc9, 0x65, 0xbc, 0x8a, 0x43, 0x1b, 0xaa,
	0xb6, 0xbf, 0x39, 0x85, 0x98, 0xdc, 0xe2, 0x60, 0x9a, 0x40, 0xc0, 0x43, 0xa2, 0x3d, 0x96, 0x5d,
	0x5d, 0xdb, 0x11, 0x54, 0xd3, 0xd5, 0xe3, 0x65, 0x42, 0xde, 0xbd, 0xf3, 0x23, 0xcb, 0xed, 0x4e,
	0x7e, 0xd1, 0x5b, 0x0e, 0xb3, 0x2b, 0xcd, 0xed, 0x95, 0xed, 0x27, 0x03, 0xbe, 0x8f, 0x05, 0xa6,
	0x8c, 0xb2, 0x48, 0xab, 0x08, 0x1c, 0x10, 0xd4, 0x81, 0xdf, 0x57, 0x3c, 0xa4, 0x93, 0xe5, 0x8b,
	0xd6, 0xda, 0xf0, 0x57, 0x27, 0xe7, 0xad, 0x95, 0x47, 0x12, 0x9d, 0x42, 0xeb, 0x82, 0xa8, 0xd7,
	0x5e, 0xd6, 0x9d, 0x9d, 0xdf, 0xaf, 0xb5, 0x8b, 0x25, 0xea, 0x82, 0xe5, 0x2d, 0x7c, 0x19, 0x08,
	0xea, 0x93, 0xe2, 0xdb, 0xa6, 0xb3, 0xe7, 0x2f, 0x5f, 0x54, 0x38, 0x34, 0xba, 0xb5, 0x9b, 0xaa,
	0xd3, 0xd9, 0xc4, 0xe4, 0x7f, 0xd6, 0x5f, 0xcc, 0xd1, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62,
	0x89, 0x5d, 0xe2, 0x44, 0x03, 0x00, 0x00,
}
