# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'diag.proto')
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ndiag.proto\x12\x04\x64iag"3\n\x06PodRef\x12\n\n\x02ns\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07pod_uid\x18\x03 \x01(\t"G\n\x0e\x43ollectRequest\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\x0b\n\x03job\x18\x02 \x01(\t\x12\x1a\n\x04pods\x18\x03 \x03(\x0b\x32\x0c.diag.PodRef"/\n\nCollectAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"f\n\rUploadRequest\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\x0b\n\x03job\x18\x02 \x01(\t\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x11\n\tnamespace\x18\x06 \x01(\t"\x1d\n\tUploadAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x45\n\tCollector\x12\x38\n\x0eTriggerCollect\x12\x14.diag.CollectRequest\x1a\x10.diag.CollectAck2B\n\x08Uploader\x12\x36\n\x0cUploadResult\x12\x13.diag.UploadRequest\x1a\x0f.diag.UploadAck(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_PODREF']._serialized_start = 20
    _globals['_PODREF']._serialized_end = 71
    _globals['_COLLECTREQUEST']._serialized_start = 73
    _globals['_COLLECTREQUEST']._serialized_end = 144
    _globals['_COLLECTACK']._serialized_start = 146
    _globals['_COLLECTACK']._serialized_end = 193
    _globals['_UPLOADREQUEST']._serialized_start = 195
    _globals['_UPLOADREQUEST']._serialized_end = 297
    _globals['_UPLOADACK']._serialized_start = 299
    _globals['_UPLOADACK']._serialized_end = 328
    _globals['_COLLECTOR']._serialized_start = 330
    _globals['_COLLECTOR']._serialized_end = 399
    _globals['_UPLOADER']._serialized_start = 401
    _globals['_UPLOADER']._serialized_end = 467
# @@protoc_insertion_point(module_scope)
