# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# pylint: disable=no-member  # diag_pb2 members are dynamically generated by the protobuf builder, invisible to static checks
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from diagproto import diag_pb2 as diag__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in diag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorStub:
    """Collector-side service: receives collect triggers (one per node on the DaemonSet)."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerCollect = channel.unary_unary(
            '/diag.Collector/TriggerCollect',
            request_serializer=diag__pb2.CollectRequest.SerializeToString,
            response_deserializer=diag__pb2.CollectAck.FromString,
            _registered_method=True,
        )


class CollectorServicer:
    """Collector-side service: receives collect triggers (one per node on the DaemonSet)."""

    def TriggerCollect(self, request, context):
        """Trigger one node's collect: returns accepted immediately; the collector executes asynchronously in the background and reports the result."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'TriggerCollect': grpc.unary_unary_rpc_method_handler(
            servicer.TriggerCollect,
            request_deserializer=diag__pb2.CollectRequest.FromString,
            response_serializer=diag__pb2.CollectAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('diag.Collector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('diag.Collector', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Collector:
    """Collector-side service: receives collect triggers (one per node on the DaemonSet)."""

    @staticmethod
    def TriggerCollect(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/diag.Collector/TriggerCollect',
            diag__pb2.CollectRequest.SerializeToString,
            diag__pb2.CollectAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class UploaderStub:
    """Agent-side service: receives collection results reported by the collector."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadResult = channel.stream_unary(
            '/diag.Uploader/UploadResult',
            request_serializer=diag__pb2.UploadRequest.SerializeToString,
            response_deserializer=diag__pb2.UploadAck.FromString,
            _registered_method=True,
        )


class UploaderServicer:
    """Agent-side service: receives collection results reported by the collector."""

    def UploadResult(self, request_iterator, context):
        """Report a collection result: client-streaming chunks the tar.gz.
        The first chunk carries node/job/ok/error metadata + the first data chunk; later chunks carry only data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'UploadResult': grpc.stream_unary_rpc_method_handler(
            servicer.UploadResult,
            request_deserializer=diag__pb2.UploadRequest.FromString,
            response_serializer=diag__pb2.UploadAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('diag.Uploader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('diag.Uploader', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Uploader:
    """Agent-side service: receives collection results reported by the collector."""

    @staticmethod
    def UploadResult(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/diag.Uploader/UploadResult',
            diag__pb2.UploadRequest.SerializeToString,
            diag__pb2.UploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
