// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: config.proto

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Recover_Register_FullMethodName           = "/Recover/Register"
	Recover_SubscribeRankTable_FullMethodName = "/Recover/SubscribeRankTable"
)

// RecoverClient is the client API for Recover service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoverClient interface {
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	SubscribeRankTable(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeRankTableClient, error)
}

type recoverClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoverClient(cc grpc.ClientConnInterface) RecoverClient {
	return &recoverClient{cc}
}

func (c *recoverClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) SubscribeRankTable(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeRankTableClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recover_ServiceDesc.Streams[0], Recover_SubscribeRankTable_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recoverSubscribeRankTableClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recover_SubscribeRankTableClient interface {
	Recv() (*RankTableStream, error)
	grpc.ClientStream
}

type recoverSubscribeRankTableClient struct {
	grpc.ClientStream
}

func (x *recoverSubscribeRankTableClient) Recv() (*RankTableStream, error) {
	m := new(RankTableStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecoverServer is the server API for Recover service.
// All implementations must embed UnimplementedRecoverServer
// for forward compatibility
type RecoverServer interface {
	Register(context.Context, *ClientInfo) (*Status, error)
	SubscribeRankTable(*ClientInfo, Recover_SubscribeRankTableServer) error
	mustEmbedUnimplementedRecoverServer()
}

// UnimplementedRecoverServer must be embedded to have forward compatible implementations.
type UnimplementedRecoverServer struct {
}

func (UnimplementedRecoverServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRecoverServer) SubscribeRankTable(*ClientInfo, Recover_SubscribeRankTableServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRankTable not implemented")
}
func (UnimplementedRecoverServer) mustEmbedUnimplementedRecoverServer() {}

// UnsafeRecoverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoverServer will
// result in compilation errors.
type UnsafeRecoverServer interface {
	mustEmbedUnimplementedRecoverServer()
}

func RegisterRecoverServer(s grpc.ServiceRegistrar, srv RecoverServer) {
	s.RegisterService(&Recover_ServiceDesc, srv)
}

func _Recover_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_SubscribeRankTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoverServer).SubscribeRankTable(m, &recoverSubscribeRankTableServer{stream})
}

type Recover_SubscribeRankTableServer interface {
	Send(*RankTableStream) error
	grpc.ServerStream
}

type recoverSubscribeRankTableServer struct {
	grpc.ServerStream
}

func (x *recoverSubscribeRankTableServer) Send(m *RankTableStream) error {
	return x.ServerStream.SendMsg(m)
}

// Recover_ServiceDesc is the grpc.ServiceDesc for Recover service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recover_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recover",
	HandlerType: (*RecoverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Recover_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRankTable",
			Handler:       _Recover_SubscribeRankTable_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "config.proto",
}
