// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type RankTableStream struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	RankTable            string   `protobuf:"bytes,2,opt,name=rankTable,proto3" json:"rankTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankTableStream) Reset()         { *m = RankTableStream{} }
func (m *RankTableStream) String() string { return proto.CompactTextString(m) }
func (*RankTableStream) ProtoMessage()    {}
func (*RankTableStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *RankTableStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankTableStream.Unmarshal(m, b)
}
func (m *RankTableStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankTableStream.Marshal(b, m, deterministic)
}
func (m *RankTableStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankTableStream.Merge(m, src)
}
func (m *RankTableStream) XXX_Size() int {
	return xxx_messageInfo_RankTableStream.Size(m)
}
func (m *RankTableStream) XXX_DiscardUnknown() {
	xxx_messageInfo_RankTableStream.DiscardUnknown(m)
}

var xxx_messageInfo_RankTableStream proto.InternalMessageInfo

func (m *RankTableStream) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RankTableStream) GetRankTable() string {
	if m != nil {
		return m.RankTable
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "config.Status")
	proto.RegisterType((*ClientInfo)(nil), "config.ClientInfo")
	proto.RegisterType((*RankTableStream)(nil), "config.RankTableStream")
}

func init() {
	proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4)
}

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x0c, 0xb8, 0xd8,
	0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x66, 0x5e, 0x5a, 0xbe, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0x64, 0xc6, 0xc5, 0xe5, 0x9c, 0x93, 0x99, 0x9a, 0x57, 0xe2,
	0x99, 0x97, 0x96, 0x2f, 0x24, 0xc2, 0xc5, 0x9a, 0x95, 0x9f, 0xe4, 0x99, 0x02, 0xd6, 0xc6, 0x19,
	0x04, 0xe1, 0x80, 0xf4, 0x15, 0xe5, 0xe7, 0xa4, 0xc2, 0xf4, 0x81, 0xd8, 0x4a, 0xae, 0x5c, 0xfc,
	0x41, 0x89, 0x79, 0xd9, 0x21, 0x89, 0x49, 0x39, 0xa9, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x38,
	0x34, 0xcb, 0x70, 0x71, 0x16, 0xc1, 0x14, 0x42, 0x4d, 0x40, 0x08, 0x18, 0x35, 0x32, 0x72, 0x41,
	0xdd, 0x2e, 0x64, 0xc0, 0xc5, 0x11, 0x94, 0x9a, 0x9e, 0x59, 0x5c, 0x92, 0x5a, 0x24, 0x24, 0xa4,
	0x07, 0xf5, 0x1e, 0xc2, 0x6d, 0x52, 0x7c, 0x30, 0x31, 0x88, 0x0f, 0x95, 0x18, 0x84, 0x5c, 0xb9,
	0x84, 0x82, 0x4b, 0x93, 0x8a, 0x93, 0x8b, 0x32, 0x93, 0x52, 0xe1, 0x8e, 0xc1, 0xaa, 0x57, 0x1c,
	0x26, 0x86, 0xe6, 0x66, 0x25, 0x06, 0x03, 0x46, 0x27, 0xae, 0x28, 0x0e, 0x3d, 0x6b, 0x88, 0x7c,
	0x12, 0x1b, 0x38, 0x3c, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x70, 0xec, 0xf8, 0x5f,
	0x01, 0x00, 0x00,
}
