#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""node-collector: runs on the NPU worker node (DaemonSet).

Collects according to collect_manifest.yaml (v3/entities), organizes the output into the
directory layout expected by ascend-fd parse, runs ascend-fd parse locally, then tars the
cleaned artifacts and actively reports them to the agent via gRPC UploadResult.

Mount paths are resolved by the collector-local pod -> host_paths table (pathmap, sourced
from the global CM), not dispatched by the agent. During diagnosis the agent queries the
central relation table by jobname for all pods -> nodes, and dispatches
TriggerCollect {node, job, pods:[{pod_uid,ns,name}]} to each node; the collector then
collects + cleans in the background and reports the result via UploadResult (failures are
also reported). Asynchronous model: the agent keeps no long-lived connections.

Collect contract field priority (executed by _gather):
  env          : highest. Read the pod env value (in-container path, recorded by agent-core
                 in the pathmap CM) -> reverse-lookup the host path via pathmap -> copy to
                 {collect_dir}/name. When it succeeds, paths/commands/mount_keywords are
                 skipped; on failure (value not recorded / not resolvable) the lower-priority
                 fields run.
  paths        : equal priority with commands. In-pod path -> match the pod mount pairs by
                 container path -> reverse-lookup the host path -> copy (fall back to reading
                 the host paths directly when no mount pair matches). dl_log/host_log paths
                 are node host paths read directly without pathmap.
  commands     : equal priority with paths. Run whitelisted commands in a temp dir (shell) ->
                 copy all generated files to {collect_dir}/name -> clean up the temp dir;
                 commands without a > redirect capture stdout/stderr as {name}_stdout.txt.
                 The WHOLE command string must exactly match the ALLOWED_COMMANDS whitelist
                 (dmesg/dmidecode/msnpureport invocations); tampered strings are skipped.
  mount_keywords : lowest (used only when paths is not configured, e.g. an entity with env
                 configured but the pod lookup finds no value). Match mount pairs by keyword
                 (first hit wins); if no direct hit, scan the mount host path subdirectories
                 for a subdir containing the keyword
"""

# pylint: disable=no-member  # diag_pb2 members are dynamically generated by the protobuf builder, invisible to static checks

from __future__ import annotations

import glob
import io
import json
import logging
import os
import shutil
import subprocess
import tarfile
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import grpc

from clusterops_common import quota
from clusterops_common.log import init_logging
from node_collector.pathmap import (
    get_pathmap,
    init_manifest_watch,
    init_pathmap,
    load_manifest as _load_manifest_from_cm,
    shutdown_manifest_watch,
    shutdown_pathmap,
)
from diagproto import diag_pb2, diag_pb2_grpc

logger = logging.getLogger(__name__)

# ---- Collect contract fields / entity mode constants (kept consistent with collect_manifest.yaml and pathmap) ----
KEY_ENTITIES = "entities"
KEY_NAME = "name"
KEY_COMMANDS = "commands"
KEY_PATHS = "paths"
KEY_ENV = "env"
KEY_MOUNT_KEYWORDS = "mount_keywords"
ENTITY_HOST_LOG = "host_log"
ENTITY_DL_LOG = "dl_log"
# Commands allowed to run on the node. A command is run only when its whitespace-normalized
# string matches one of these strings exactly.
ALLOWED_COMMANDS = frozenset(
    {
        "/usr/bin/dmesg -T | tail -n 100000 > dmesg",
        "/usr/sbin/dmidecode > dmidecode.txt",
        "/usr/bin/msnpureport --docker",
    }
)


def _cmd_allowed(cmd: str) -> bool:
    """Whole-string whitelist check: the command (whitespace-collapsed) must match exactly."""
    return " ".join(cmd.split()) in ALLOWED_COMMANDS


WORK_ROOT = Path(os.environ.get("COLLECTOR_WORK_ROOT") or "/user/clusterops/node-collector")
COLLECTOR_PORT = int(os.environ.get("COLLECTOR_PORT", "9720"))
ASCEND_FD = os.environ.get("ASCEND_FD_BIN", "ascend-fd")
AGENT_ADDR = os.environ.get("AGENT_ADDR", "agent-core.mindx-dl:9710")
UPLOAD_CHUNK = 64 * 1024
UPLOAD_TIMEOUT = float(os.environ.get("UPLOAD_TIMEOUT", "600"))
UPLOAD_RETRIES = int(os.environ.get("UPLOAD_RETRIES", "3"))

_manifest: dict | None = None


def _load_manifest() -> dict:
    # Prefer the ConfigMap <collect-manifest> (user site override), fall back to the
    # built-in collect_manifest.yaml in the image.
    if _manifest is not None:
        return _manifest
    return _load_manifest_from_cm()


class PodRef:
    """Reference to a pod to be collected (local equivalent of the gRPC PodRef)."""

    __slots__ = ("ns", "name", "pod_uid")

    def __init__(self, ns: str, name: str, pod_uid: str):
        self.ns = ns
        self.name = name
        self.pod_uid = pod_uid


# --------------------------------------------------------------------------- #
# gRPC service (agent --Collect--> collector)
# --------------------------------------------------------------------------- #
class _CollectError(Exception):
    """Collect/parse failure carrying the detail reported to the agent."""


class CollectorClient:
    """Node collect executor (object-oriented): collect + local parse -> tar.gz -> gRPC upload.

    State is held on the instance (work_root / ascend_fd / agent_addr / upload chunk / timeout /
    retries); production uses the module-level singleton collector_client.
    """

    def __init__(
        self,
        work_root: Path | str = WORK_ROOT,
        ascend_fd: str = ASCEND_FD,
        agent_addr: str = AGENT_ADDR,
        upload_chunk: int = UPLOAD_CHUNK,
        upload_timeout: float = UPLOAD_TIMEOUT,
        upload_retries: int = UPLOAD_RETRIES,
    ) -> None:
        self.work_root = Path(work_root)
        self.ascend_fd = ascend_fd
        self.agent_addr = agent_addr
        self.upload_chunk = upload_chunk
        self.upload_timeout = upload_timeout
        self.upload_retries = upload_retries

    # ---- Collect execution (per v3 entities fields) ----
    @staticmethod
    def _glob_base(pat: str) -> str:
        """Directory prefix of a glob pattern before the first wildcard segment.

        Used to preserve the relative directory structure when copying matched files
        (e.g. <plog>/** keeps run/ debug/ security/ subdirs instead of flattening).
        """
        fixed: list[str] = []
        for seg in pat.split("/"):
            if any(ch in seg for ch in "*?["):
                break
            fixed.append(seg)
        base = "/".join(fixed)
        return base.rstrip("/") or "/"

    @staticmethod
    def _collect_host_path(dst: Path, paths: list[str]) -> None:
        """Copy the whole host path tree (files + directories, empty dirs included) into dst.

        For each glob pattern, keep its fixed prefix as the base to preserve the relative
        directory structure (e.g. <plog>/** keeps run/ debug/ security/ subdirs instead of
        flattening). A matched directory is copied as a whole tree so that empty
        subdirectories (e.g. security/ with no files) are preserved too; a file outside the
        prefix is copied flat to dst's root.
        """
        for pat in paths:
            base = CollectorClient._glob_base(pat)
            for matched in glob.glob(pat, recursive=True):
                p = Path(matched)
                try:
                    if p.is_dir():
                        try:
                            rel = p.relative_to(base)
                        except ValueError:
                            rel = Path(p.name)  # not under the fixed prefix -> flat to dst root
                        target = dst / rel
                        target.mkdir(parents=True, exist_ok=True)
                        shutil.copytree(p, target, dirs_exist_ok=True)
                    elif p.is_file():
                        try:
                            rel = p.relative_to(base)
                        except ValueError:
                            rel = Path(p.name)  # not under the fixed prefix -> flat to dst root
                        target = dst / rel.parent
                        target.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(p, target / rel.name)
                except OSError:
                    continue

    @staticmethod
    def _run_commands(dst: Path, commands: list[str], name: str) -> None:
        """Run whitelisted commands in a temp dir (shell); copy all generated files to dst
        (keeping the relative structure), then clean up the temp dir.

        Only commands whose whole string matches ALLOWED_COMMANDS (_cmd_allowed) are run;
        anything else is skipped with a warning. Commands without a > redirect capture
        stdout/stderr as {name}_stdout.txt.
        """
        tmp = Path(tempfile.mkdtemp(prefix="ascend-fd-cmd-"))
        try:
            for cmd in commands:
                if not _cmd_allowed(cmd):
                    logger.warning(
                        "skipping disallowed collect command: entity=%s cmd=%s (allowed: %s)",
                        name,
                        cmd,
                        sorted(ALLOWED_COMMANDS),
                    )
                    continue
                logger.info("executing collect commands: entity=%s cmd=%s", name, cmd)
                try:
                    # whole command string already whitelist-checked by _cmd_allowed above
                    r = subprocess.run(
                        cmd, shell=True, check=False, capture_output=True, text=True, timeout=600, cwd=tmp
                    )  # nosec B602
                except (OSError, ValueError, subprocess.TimeoutExpired):
                    continue
                out = (r.stdout or "") + (r.stderr or "")
                if out.strip():
                    (tmp / f"{name}_stdout.txt").write_text(out, encoding="utf-8", errors="replace")
            for p in tmp.rglob("*"):
                if p.is_file():
                    rel = p.relative_to(tmp)
                    target = dst / rel.parent
                    target.mkdir(parents=True, exist_ok=True)
                    try:
                        shutil.copy2(p, target / p.name)
                    except OSError:
                        continue
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    @staticmethod
    def _looks_like(keywords: list[str], s: str) -> bool:
        s = (s or "").lower()
        return any(k in s for k in keywords)

    def _match_path_pairs(self, pairs: list[str], container_paths: list[str]) -> list[tuple[str, str]]:
        """From all host:container pairs, pick those whose container side matches a configured container path (== or prefix)."""
        matched: list[tuple[str, str]] = []
        for pair in pairs:
            host, container = pair.split(":", 1)
            c = (container or "").rstrip("/")
            for cp in container_paths:
                cp = (cp or "").rstrip("/")
                if not cp:
                    continue
                if c == cp or c.startswith(cp + "/"):
                    if (host, container) not in matched:
                        matched.append((host, container))
                    break
        return matched

    def _collect_mount_keywords(self, dst: Path, entity: dict, pods: list[PodRef]) -> None:
        """mount_keywords entity: match the pod's all mount pairs by keyword (first hit wins); if none match, scan the host path subdirectories for a subdir containing the keyword."""
        keywords = [k.lower() for k in entity.get("mount_keywords", [])]
        for pod in pods:
            pairs = get_pathmap().all_pairs(pod.pod_uid)
            if not pairs:
                continue
            chosen: str | None = None
            for pair in pairs:
                host, container = pair.split(":", 1)
                if self._looks_like(keywords, host) or self._looks_like(keywords, container):
                    chosen = host
                    break
            if chosen:
                logger.info(
                    "mount keyword matched: entity=%s pod=%s host=%s kw=%s", entity["name"], pod.name, chosen, keywords
                )
                self._collect_host_path(dst, [str(Path(chosen) / "**")])
                continue
            # No keyword match: scan each mount host path's subdirectories for one containing the keyword
            for pair in pairs:
                host, _ = pair.split(":", 1)
                hp = Path(host)
                if not hp.is_dir():
                    continue
                for sub in hp.iterdir():
                    if sub.is_dir() and self._looks_like(keywords, sub.name):
                        logger.info(
                            "mount subdir matched: entity=%s pod=%s dir=%s kw=%s",
                            entity["name"],
                            pod.name,
                            sub,
                            keywords,
                        )
                        self._collect_host_path(dst, [str(sub / "**")])

    @staticmethod
    def _resolve_container_to_host(pairs: list[str], container_path: str) -> str | None:
        """Map an in-container path to the host path via the pod's host:container mount pairs (longest prefix wins)."""
        cp = (container_path or "").rstrip("/")
        if not cp:
            return None
        best_host: str | None = None
        best_prefix_len = -1
        for pair in pairs:
            host, container = pair.split(":", 1)
            c = (container or "").rstrip("/")
            if not c:
                continue
            if cp == c or cp.startswith(c + "/"):
                candidate = host + cp[len(c) :]
                if len(c) > best_prefix_len:
                    best_host, best_prefix_len = candidate, len(c)
        return best_host

    def _collect_env_entity(self, dst: Path, entity: dict, pods: list[PodRef]) -> bool:
        """mode=env: read the pod env value (recorded by agent-core in the pathmap CM) ->
        reverse-lookup the host path via pathmap -> collect. Returns True when at least one
        pod's env resolved to a host path.

        When the env value is not recorded (pod already deleted / env absent) or cannot be
        resolved, returns False so the caller can fall back to mount_keywords / paths.
        """
        env_name = entity.get(KEY_ENV)
        if not env_name:
            return False
        collected = False
        for pod in pods:
            pm = get_pathmap()
            value = pm.pod_env(pod.pod_uid, env_name)
            if not value:
                continue
            pairs = pm.all_pairs(pod.pod_uid)
            host = self._resolve_container_to_host(pairs, value)
            if not host:
                logger.warning(
                    "env value not resolvable to a host path: entity=%s pod=%s env=%s container=%s pairs=%d",
                    entity["name"],
                    pod.name,
                    env_name,
                    value,
                    len(pairs),
                )
                continue
            logger.info(
                "collecting entity %s via pod env: pod=%s env=%s container=%s host=%s",
                entity["name"],
                pod.name,
                env_name,
                value,
                host,
            )
            self._collect_host_path(dst, [str(Path(host) / "**")])
            collected = True
        return collected

    def _collect_host_log(self, dst: Path, entity: dict) -> None:
        """host_log entity: read node host paths directly + run on-site commands (without pathmap)."""
        if entity.get(KEY_COMMANDS):
            logger.info("collecting entity %s: running commands -> %s", ENTITY_HOST_LOG, entity[KEY_COMMANDS])
            self._run_commands(dst, entity[KEY_COMMANDS], ENTITY_HOST_LOG)
        if entity.get(KEY_PATHS):
            logger.info("collecting entity %s: reading host paths directly -> %s", ENTITY_HOST_LOG, entity[KEY_PATHS])
            self._collect_host_path(dst, entity[KEY_PATHS])

    def _run_entity_commands(self, dst: Path, name: str, entity: dict) -> None:
        """Run the commands configured on the entity (self-contained, independent of pathmap)."""
        if entity.get(KEY_COMMANDS):
            logger.info("collecting entity %s: running commands -> %s", name, entity[KEY_COMMANDS])
            self._run_commands(dst, entity[KEY_COMMANDS], name)

    @staticmethod
    def _collect_direct_host_paths(dst: Path, paths: list[str]) -> None:
        """Read host paths directly (no pathmap matching), emitting a subdir per path basename.

        Used by dl_log: its paths are host paths of standalone DaemonSet/Deployment components
        (noded/devicePlugin/clusterd). The task pod does not mount them, and pathmap only records
        task-pod mount pairs, so matching against task pods is skipped entirely - a task pod that
        happens to mount the same container path would otherwise produce wrong dl_log content.
        """
        for pat in paths:
            base = Path(pat.rstrip("/")).name or "files"
            tgt = dst / base
            tgt.mkdir(parents=True, exist_ok=True)
            CollectorClient._collect_host_path(tgt, [str(Path(pat) / "**")])

    def _collect_paths(self, dst: Path, name: str, entity: dict, pods: list[PodRef]) -> None:
        """paths entity: match the task pods' all mount pairs by container path; fall back to reading host paths directly if there are none.

        dl_log is a special case: its paths are host paths of standalone components, read
        directly without task-pod mount-pair matching (see _collect_direct_host_paths).
        """
        container_paths = [c for c in (entity.get(KEY_PATHS, []) or []) if c]
        if not container_paths:
            return
        if name == ENTITY_DL_LOG:
            self._collect_direct_host_paths(dst, container_paths)
            return
        matched_any = False
        for pod in pods:
            pairs = get_pathmap().all_pairs(pod.pod_uid)
            matched = self._match_path_pairs(pairs, container_paths)
            if not matched:
                continue
            matched_any = True
            logger.info(
                "collecting entity %s: matching task pod mount pairs by container path, pod=%s matched=%d",
                name,
                pod.name,
                len(matched),
            )
            for host, container in matched:
                target = dst / (Path(container.rstrip("/")).name if name == ENTITY_DL_LOG else "")
                target.mkdir(parents=True, exist_ok=True)
                self._collect_host_path(target, [str(Path(host) / "**")])
        if matched_any:
            return
        logger.info(
            "collecting entity %s: no mount pair on the task pod, fall back to reading host paths directly -> %s",
            name,
            container_paths,
        )
        self._collect_direct_host_paths(dst, container_paths)

    def _gather(self, manifest: dict, collect_dir: Path, pods: list[PodRef]) -> None:
        """Execute collection per the v3 contract.

        Field priority: env > paths = commands > mount_keywords. When a higher-priority
        field is configured and collects successfully, lower-priority fields are skipped.
        env reads the pod env value (e.g. ASCEND_PROCESS_LOG_PATH, recorded by agent-core
        in the pathmap CM) and reverse-looks-up the host path; paths matches the pod mount
        pairs by container path (falling back to reading host paths directly); commands run
        whitelisted on-site commands. mount_keywords is the lowest-priority fallback used
        only when paths is not configured. host_log reads node host paths directly.
        """
        for entity in manifest.get(KEY_ENTITIES, []):
            name = entity[KEY_NAME]
            dst = collect_dir / name
            dst.mkdir(parents=True, exist_ok=True)
            if name == ENTITY_HOST_LOG:
                self._collect_host_log(dst, entity)
                continue
            # env is the highest priority: skip paths/commands/mount_keywords when it succeeds
            if entity.get(KEY_ENV):
                # resolve the pod env via pathmap to the host path; on failure fall back to the lower-priority fields
                if self._collect_env_entity(dst, entity, pods):
                    continue
            # paths and commands are equal priority: both run when env is not configured or failed
            self._run_entity_commands(dst, name, entity)
            if entity.get(KEY_PATHS):
                self._collect_paths(dst, name, entity, pods)
            elif entity.get(KEY_MOUNT_KEYWORDS):
                self._collect_mount_keywords(dst, entity, pods)
            else:
                logger.info(
                    "collecting entity %s: no paths/mount_keywords, only commands collected",
                    name,
                )

    def collect(self, node: str, ns: str, job: str, pods: list[PodRef]) -> bytes:
        """Collect + local parse -> pack into tar.gz and return (for gRPC streaming upload).

        Artifacts are organized by date + ns_job like the agent
        (WORK_ROOT/{YYYYMMDD}/{ns}_{job}/collect + parse-output), so each task's
        collected/cleaned data stays in its own directory and different tasks (or the
        same task name in different namespaces) never overwrite each other.
        """
        manifest = _load_manifest()
        work = self.work_root / time.strftime("%Y%m%d") / f"{ns}_{job}"
        shutil.rmtree(work, ignore_errors=True)
        collect_dir = work / "collect"
        out_dir = work / "parse-output"
        collect_dir.mkdir(parents=True, exist_ok=True)
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info("starting collect: node=%s ns=%s job=%s pods=%d", node, ns, job, len(pods))
        try:
            self._gather(manifest, collect_dir, pods)
        except Exception as e:  # noqa: BLE001
            logger.exception("gather failed: node=%s", node)
            raise _CollectError(f"gather failed: {e}") from e

        cmd = [self.ascend_fd, "parse", "-i", str(collect_dir), "-o", str(out_dir)]
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=1800)
        except subprocess.CalledProcessError as e:
            logger.error("ascend-fd parse failed: node=%s err=%s", node, (e.stderr or e.stdout)[-2000:])
            raise _CollectError(f"ascend-fd parse failed: {(e.stderr or e.stdout)[-2000:]}") from e
        logger.info("collect + parse completed: node=%s", node)

        buf = io.BytesIO()
        with tarfile.open(fileobj=buf, mode="w:gz") as tf:
            tf.add(out_dir, arcname=".")
        buf.seek(0)
        return buf.read()

    def _upload_stream(self, meta: dict, data: bytes):
        """client-streaming generator: the first chunk carries node/job/ns/ok/error + the first data chunk, subsequent chunks carry only data."""
        if not data:
            yield diag_pb2.UploadRequest(
                node=meta["node"],
                job=meta["job"],
                namespace=meta.get("namespace", ""),
                ok=meta["ok"],
                error=meta.get("error", ""),
            )
            return
        yield diag_pb2.UploadRequest(
            node=meta["node"],
            job=meta["job"],
            namespace=meta.get("namespace", ""),
            ok=True,
            error="",
            data=data[: self.upload_chunk],
        )
        for i in range(self.upload_chunk, len(data), self.upload_chunk):
            yield diag_pb2.UploadRequest(data=data[i : i + self.upload_chunk])

    def upload_result(self, meta: dict, data: bytes) -> bool:
        """Upload the successfully collected tar.gz to the agent (with retries)."""
        for attempt in range(self.upload_retries):
            try:
                with grpc.insecure_channel(self.agent_addr) as ch:
                    diag_pb2_grpc.UploaderStub(ch).UploadResult(
                        self._upload_stream(meta, data), timeout=self.upload_timeout
                    )
                return True
            except grpc.RpcError:
                if attempt == self.upload_retries - 1:
                    return False
                time.sleep(min(2**attempt, 8))
        return False

    def upload_failure(self, meta: dict, error: str) -> None:
        """Report the failure result to the agent (no data chunks)."""
        try:
            with grpc.insecure_channel(self.agent_addr) as ch:
                diag_pb2_grpc.UploaderStub(ch).UploadResult(
                    self._upload_stream({**meta, "ok": False, "error": error}, b""), timeout=60
                )
        except grpc.RpcError:
            pass

    def run_and_upload(self, request: diag_pb2.CollectRequest) -> None:
        """Background thread: collect + clean -> upload success tar / failure error."""
        ns = request.pods[0].ns if request.pods else "default"
        meta = {"node": request.node, "job": request.job, "namespace": ns}
        try:
            pods = [PodRef(ns=p.ns, name=p.name, pod_uid=p.pod_uid) for p in request.pods]
            data = self.collect(request.node, ns, request.job, pods)
            ok = self.upload_result(meta, data)
            if not ok:
                self.upload_failure(meta, "upload failed after retries")
            logger.info(
                "uploading collect result: node=%s job=%s ns=%s ok=%s size=%d",
                request.node,
                request.job,
                ns,
                ok,
                len(data),
            )
        except _CollectError as e:
            logger.error("collect failed and reported: node=%s job=%s err=%s", request.node, request.job, e)
            self.upload_failure(meta, str(e))
        except Exception as e:  # noqa: BLE001
            logger.exception("collect exception: node=%s job=%s", request.node, request.job)
            self.upload_failure(meta, f"collect failed: {e}")
        finally:
            try:
                quota.enforce_quota(self.work_root)
            except Exception:  # noqa: BLE001  # quota pruning must not break the collect thread
                logger.exception("workspace quota enforcement failed: node=%s job=%s", request.node, request.job)


# Production singleton reused by the TriggerCollect background thread
collector_client = CollectorClient()

# ---- TriggerCollect concurrency control & per-(node, job) dedup ----
_COLLECT_LOCK = threading.Lock()
_active_collects: set[tuple[str, str]] = set()
MAX_CONCURRENT_COLLECTS = int(os.environ.get("MAX_CONCURRENT_JOBS", "10"))


def _run_collect(request: diag_pb2.CollectRequest, key: tuple[str, str]) -> None:
    """Background thread body: run collect+upload, then release the dedup slot."""
    try:
        collector_client.run_and_upload(request)
    finally:
        with _COLLECT_LOCK:
            _active_collects.discard(key)


class CollectorServicer(diag_pb2_grpc.CollectorServicer):
    """node-collector gRPC service: trigger collect returns immediately, collects + uploads asynchronously in the background."""

    def TriggerCollect(self, request: diag_pb2.CollectRequest, context):  # noqa: N802
        key = (request.node, request.job)
        with _COLLECT_LOCK:
            if key in _active_collects:
                logger.warning("duplicate TriggerCollect rejected: node=%s job=%s", request.node, request.job)
                return diag_pb2.CollectAck(accepted=False, message="duplicate job")
            if len(_active_collects) >= MAX_CONCURRENT_COLLECTS:
                logger.warning(
                    "TriggerCollect concurrency limit reached: %d/%d",
                    len(_active_collects),
                    MAX_CONCURRENT_COLLECTS,
                )
                return diag_pb2.CollectAck(accepted=False, message="concurrent jobs exceeded")
            _active_collects.add(key)

        pods = [{"ns": p.ns, "name": p.name, "pod_uid": p.pod_uid} for p in request.pods]
        logger.info(
            "TriggerCollect received: node=%s job=%s pods=%d data=%s",
            request.node,
            request.job,
            len(pods),
            json.dumps(pods, ensure_ascii=False),
        )
        try:
            t = threading.Thread(target=_run_collect, args=(request, key), daemon=True)
            t.start()
            return diag_pb2.CollectAck(accepted=True, message="started")
        except Exception as e:  # noqa: BLE001
            with _COLLECT_LOCK:
                _active_collects.discard(key)
            context.abort(grpc.StatusCode.INTERNAL, f"trigger failed: {e}")
            return diag_pb2.CollectAck(
                accepted=False, message=""
            )  # unreachable: abort raises, keeps the return consistent


def _build_grpc_server() -> grpc.Server:
    """Build the collector gRPC server (binding COLLECTOR_PORT=9720)."""
    server = grpc.server(ThreadPoolExecutor(max_workers=4))
    diag_pb2_grpc.add_CollectorServicer_to_server(CollectorServicer(), server)
    server.add_insecure_port(f"0.0.0.0:{COLLECTOR_PORT}")
    return server


def serve() -> None:
    """gRPC server entry point (python -m / console script): starts the local pathmap + collect service."""
    init_logging(log_dir="/var/log/mindx-dl/node-collector", log_file="node-collector.log")  # persist logs to disk
    init_pathmap()
    init_manifest_watch()  # watch collect-manifest CM (override of the built-in file) + log updates
    server = _build_grpc_server()
    server.start()
    logger.info("diag node-collector gRPC listening on :%s", COLLECTOR_PORT)
    try:
        server.wait_for_termination()
    finally:
        logger.info("diag node-collector stopped: closing gRPC :%s", COLLECTOR_PORT)
        shutdown_manifest_watch()
        shutdown_pathmap()


if __name__ == "__main__":
    serve()
