apiVersion: v1
kind: ServiceAccount
metadata:
  name: rdma-shared-dp-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rdma-shared-dp-cm-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "delete", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rdma-shared-dp-cm-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rdma-shared-dp-cm-role
subjects:
  - kind: ServiceAccount
    name: rdma-shared-dp-sa
    namespace: kube-system
