{{- if and .Values.enableDpcOrDtfs (not (eq (kindOf .Values.enableDpcOrDtfs) "bool")) -}}
  {{- fail (printf "enableDpcOrDtfs must be a boolean value, got %s: %v" (kindOf .Values.enableDpcOrDtfs) .Values.enableDpcOrDtfs) -}}
{{- end -}}

{{- $key := "default" -}}
{{- if eq (.Values.enableDpcOrDtfs | toString)  "true" -}}
{{- $key = "dpc" -}}
{{- end -}}

{{- $filePath := printf "yamls/%s/**.yaml" $key -}}

{{- $files := .Files.Glob $filePath -}}
{{- if not $files -}}
  {{- fail (printf "No files found matching pattern: %s" $filePath) -}}
{{- end -}}

{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob $filePath }}
  {{- with $currentScope }}
    {{- $content := $.Files.Get $path -}}
    {{- tpl $content $ }}
---
  {{- end }}
{{- end }}
