{{- $value := .Values.enabledStorageCheck -}}

{{- $key := "default" -}}
{{- if or (eq $value "dpc") (eq $value "dtfs") (eq $value "dpc,dtfs") (eq $value "dtfs,dpc") -}}
{{- $key = "dpc" -}}
{{- else if (eq $value "container-snapshot") -}}
  {{- $key = "container-snapshot" -}}
{{- end -}}

{{- $filePath := printf "yamls/%s/**.yaml" $key -}}

{{- $files := .Files.Glob $filePath -}}
{{- if not $files -}}
  {{- fail (printf "No files found matching pattern: %s" $filePath) -}}
{{- end -}}

{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob $filePath }}
  {{- with $currentScope }}
    {{- $content := $.Files.Get $path -}}
    {{- tpl $content $ }}
---
  {{- end }}
{{- end }}
