#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Diagnosis agent toolset.

The central relation cache (agent.relcache) maintains task→pod→{node,poduid,rank}
and is queried directly by jobname; mount paths are resolved by the collector's
local pathmap and do not go through the agent.

diagnose(job, namespace): relcache.lookup -> all pod->node -> concurrently issue
TriggerCollect to each node (short-lived connection returns immediately) -> each
node's collector collects + cleans in the background, then actively reports via
UploadResult -> the agent aggregates with JobTracker, and after all arrive / timeout
-> assemble -> ascend-fd diag. Async model: no long-lived connections even with
500 nodes; collection takes ~10 min/node and can run in parallel.
Deterministic, no LLM dependency; report summarization is done by the caller
(agent.py / HTTP layer) as needed.
"""

# pylint: disable=no-member  # diag_pb2 members are dynamically generated by the protobuf builder, invisible to static analysis

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import grpc
from agent_core.constants import WORK_ROOT
from agent_core.jobs import tracker
from agent_core.k8s import K8s
from agent_core.pathmap import get_writer
from clusterops_common import quota
from diagproto import diag_pb2, diag_pb2_grpc

logger = logging.getLogger(__name__)

COLLECTOR_PORT = int(os.environ.get("COLLECTOR_PORT", "9720"))
ASCEND_FD = os.environ.get("ASCEND_FD_BIN", "ascend-fd")
COLLECT_TIMEOUT = float(
    os.environ.get("COLLECT_TIMEOUT", "600")
)  # 10 min: start diag at deadline, ignore nodes that did not upload
TRIGGER_TIMEOUT = float(os.environ.get("TRIGGER_TIMEOUT", "30"))  # TriggerCollect only confirms receipt


def _cache_root() -> Path:
    """Result cache directory: {WORK_ROOT}/cache (AGENT_CACHE_DIR overrides)."""
    override = os.environ.get("AGENT_CACHE_DIR")
    if override:
        return Path(override)
    return WORK_ROOT / "cache"


# --------------------------------------------------------------------------- #
# k8s (K8s.core() / K8s.namespace() from agent_core.k8s)
# --------------------------------------------------------------------------- #
def _collector_pod_ip(v1, node: str) -> str | None:
    """Find the IP of the collector DaemonSet pod running on the given node."""
    pods = v1.list_pod_for_all_namespaces(label_selector="app=node-collector")
    for p in pods.items:
        if p.spec.node_name == node and p.status.pod_ip:
            return p.status.pod_ip
    return None


# --------------------------------------------------------------------------- #
# collect dispatch (gRPC)
# --------------------------------------------------------------------------- #
def _trigger_node(v1, node: str, job: str, refs: list[dict]) -> dict:
    """TriggerCollect a single node (short-lived connection returns immediately); a failed trigger is recorded as the final failure."""
    pod_ip = _collector_pod_ip(v1, node)
    if not pod_ip:
        return {
            "node": node,
            "ok": False,
            "error": f"no collector pod on node {node}",
            "artifacts_tar": None,
            "worker_dir": None,
        }
    addr = f"{pod_ip}:{COLLECTOR_PORT}"
    # Ship the mount pairs + env of these pods inside the request, so the collector
    # does not need a global pathmap CM cache (resolves host paths locally per request).
    writer = get_writer()
    mounts = []
    for p in refs:
        pairs, env, pod_ip = writer.pod_pairs_env(p["pod_uid"])
        mounts.append(diag_pb2.PodMount(pod_uid=p["pod_uid"], pairs=pairs, env=env, pod_ip=pod_ip))
    req = diag_pb2.CollectRequest(
        node=node,
        job=job,
        pods=[diag_pb2.PodRef(ns=p.get("ns", "default"), name=p["name"], pod_uid=p["pod_uid"]) for p in refs],
        mounts=mounts,
    )
    try:
        with grpc.insecure_channel(addr) as ch:
            ack = diag_pb2_grpc.CollectorStub(ch).TriggerCollect(req, timeout=TRIGGER_TIMEOUT)
        if not ack.accepted:
            return {
                "node": node,
                "ok": False,
                "error": f"trigger rejected: {ack.message}",
                "artifacts_tar": None,
                "worker_dir": None,
            }
        return {"node": node, "ok": True, "error": None, "artifacts_tar": None, "worker_dir": None}
    except grpc.RpcError as e:
        detail = e.details() or e.code().name
        return {
            "node": node,
            "ok": False,
            "error": f"grpc trigger failed: {detail}",
            "artifacts_tar": None,
            "worker_dir": None,
        }


def _newer_pod(a: dict, b: dict) -> bool:
    """True if pod entry a is newer than b: a live pod beats a deleted one, otherwise later deleted_at wins."""
    if bool(a.get("deleted_at")) != bool(b.get("deleted_at")):
        return not a.get("deleted_at")  # the live (not deleted) one is newer
    return bool(a.get("deleted_at")) and a["deleted_at"] >= b["deleted_at"]


def _group_by_node(pods: list[dict]) -> dict[str, list[dict]]:
    """Group pods by node; issue once per node carrying all its pods (pod_uid/ns/name).

    host_paths are not sent: resolved by the collector's local pathmap (RFC §3.3.5).
    Pods sharing the same (node, name) are the same logical pod rescheduled on the
    same node: keep only the latest instance (_newer_pod).
    """
    latest: dict[tuple[str, str], dict] = {}  # (node, name) -> newest pod entry
    for p in pods:
        node = p.get("node")
        if not node:
            continue
        key = (node, p.get("pod_name"))
        cur = latest.get(key)
        if cur is None or _newer_pod(p, cur):
            latest[key] = p
    by_node: dict[str, list[dict]] = {}
    for (node, _name), p in latest.items():
        by_node.setdefault(node, []).append(
            {
                "pod_uid": p["pod_uid"],
                "ns": p.get("namespace", "default") or "default",
                "name": p["pod_name"],
            }
        )
    return by_node


def dispatch_collect(job: str, pods: list[dict]) -> list[dict]:
    """Dispatch asynchronously: group -> concurrent TriggerCollect (short-lived) -> JobTracker aggregates reported results.

    Nodes that fail to trigger or time out without reporting are filled in as ok=False,
    so the caller's barrier always gets a complete result.
    Returns [node->result] aligned with the node order.
    """
    by_node = _group_by_node(pods)
    nodes = list(by_node)
    if not nodes:
        logger.warning("job=%s has no valid nodes (pods not scheduled / no node)", job)
        return []
    # node name -> host ip map (from the pod list): fills host_ip into failure
    # records for nodes that never uploaded (trigger failed / timed out)
    node_ips = {p["node"]: p["host_ip"] for p in pods if p.get("node") and p.get("host_ip")}
    v1 = K8s.core()
    logger.info("dispatching collect: job=%s nodes=%d pods=%d", job, len(nodes), len(pods))
    tracker.register(job, nodes)
    # The 10-min timeout starts when the collect request is sent: start diag at deadline, ignore nodes not uploaded.
    deadline = time.monotonic() + COLLECT_TIMEOUT

    def trigger(node: str) -> None:
        res = _trigger_node(v1, node, job, by_node[node])
        if not res["ok"]:  # trigger failed immediately: record the final result, stop waiting for upload
            res["host_ip"] = node_ips.get(node)
            tracker.complete(job, node, res)

    with ThreadPoolExecutor(max_workers=min(64, len(nodes))) as ex:
        list(ex.map(trigger, nodes))

    results = tracker.wait(job, timeout=max(0.0, deadline - time.monotonic()))
    for node in nodes:
        if node not in results:  # timed out without upload
            tracker.complete(
                job,
                node,
                {
                    "node": node,
                    "ok": False,
                    "host_ip": node_ips.get(node),
                    "error": "collect timeout (no upload)",
                    "artifacts_tar": None,
                    "worker_dir": None,
                },
            )
    final = tracker.get(job)
    results = final["results"] if final else {}
    ok_nodes = [n for n in nodes if results.get(n, {}).get("ok")]
    failed_nodes = [n for n in nodes if not results.get(n, {}).get("ok")]
    if failed_nodes:
        logger.warning(
            "collect incomplete: job=%s nodes did not report collected data: %s (ok=%d/%d)",
            job,
            ", ".join(
                f"{results.get(n, {}).get('host_ip') or n}({results.get(n, {}).get('error') or 'unknown'})"
                for n in failed_nodes
            ),
            len(ok_nodes),
            len(nodes),
        )
    logger.info("collect result aggregated: job=%s ok=%d/%d", job, len(ok_nodes), len(nodes))
    return [results.get(n) for n in nodes]


# --------------------------------------------------------------------------- #
# Assemble the diag input directory
# --------------------------------------------------------------------------- #
def _has_nonempty_file(root: str | Path) -> bool:
    """True when the extracted worker dir holds at least one non-empty regular file.

    node-collector reports ok=True even when every collect entity failed, so an
    upload may legitimately carry an (almost) empty parse-output; such nodes are
    treated as empty-data nodes rather than successful workers.
    """
    try:
        for p in Path(root).rglob("*"):
            if p.is_file() and p.stat().st_size > 0:
                return True
    except OSError:
        return False
    return False


def nodes_note(incomplete_nodes: list[str], empty_nodes: list[str]) -> str:
    """Single user-facing note merging not-reported and empty-data nodes; empty string when none."""
    parts = []
    if incomplete_nodes:
        parts.append(f"the following nodes did not report collection/parsed data: {', '.join(incomplete_nodes)}")
    if empty_nodes:
        parts.append(f"the following nodes reported empty collection/parsed data: {', '.join(empty_nodes)}")
    if not parts:
        return ""
    return f"Note: {'; '.join(parts)}. The diagnosis result is based on incomplete data and is for reference only."


def assemble_diag_input(collected: list[dict], job: str, namespace: str) -> str:
    """Assemble diag input dir per ascend-fd diag 'multi-worker dump' contract.

    Layout: {WORK_ROOT}/{YYYYMMDD}/{namespace}_{job}/diag-input/{worker_name}/
    (worker_name = the machine host_ip, e.g. 192.168.1.10, so the diag report shows
    which machine each worker is on; falls back to workerN when host_ip is missing).
    Uploads are extracted straight into diag-input/worker-<node>/ (see upload.py); here
    they are renamed to the host_ip. Each worker subdir must contain server-info.json;
    ascend-fd uses the subdir name as the worker name shown in the report.
    """
    ns_job = f"{namespace}_{job}"
    diag_input = WORK_ROOT / time.strftime("%Y%m%d") / ns_job / "diag-input"
    diag_input.mkdir(parents=True, exist_ok=True)
    # clean stale worker dirs (named by host_ip or workerN), keep current worker-<node> staging
    for p in diag_input.iterdir():
        if p.is_dir() and not p.name.startswith("worker-"):
            shutil.rmtree(p, ignore_errors=True)
    worker_idx = 0
    for r in collected:
        if not r["ok"] or not r["worker_dir"]:
            continue
        src = Path(r["worker_dir"])
        if not _has_nonempty_file(src):
            continue  # empty upload: contributes no worker dir to the diag input
        name = r.get("host_ip") or f"worker{worker_idx}"
        dst = diag_input / name
        if src.is_dir():
            shutil.rmtree(dst, ignore_errors=True)
            shutil.move(str(src), str(dst))
        worker_idx += 1
    return str(diag_input)


# --------------------------------------------------------------------------- #
# Diagnosis (skill: call the ascend-fd diag CLI)
# --------------------------------------------------------------------------- #
class _DiagError(Exception):
    """ascend-fd diag failed (carries a CLI stderr summary); turned into a readable error by diagnose."""


def run_diag(diag_input_dir: str) -> tuple[str, dict, str]:
    """Run `ascend-fd diag -i <diag_input> -o <out>`, return (out_dir, diag_report, report_text).

    The output goes to the sibling {WORK_ROOT}/{YYYYMMDD}/{ns}_{job}/diag-output of the
    input (diag_input = .../{ns}_{job}/diag-input, so one level up); on failure
    raise _DiagError carrying a stderr summary instead of a raw CalledProcessError.
    report_text is the pretty report ascend-fd prints to stdout (same as a manual run);
    falls back to "" when stdout is empty.
    """
    out_dir = Path(diag_input_dir).parent / "diag-output"
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [ASCEND_FD, "diag", "-i", diag_input_dir, "-o", str(out_dir)]
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True, encoding="utf-8", timeout=1800)
        report_text = (proc.stdout or "").strip()
    except subprocess.TimeoutExpired as e:
        logger.error("ascend-fd diag timed out: %s", e)
        raise _DiagError(
            "Diagnosis error: ascend-fd diagnosis timed out, please check the relevant logs or retry later"
        ) from e
    except subprocess.CalledProcessError as e:
        detail = (e.stderr or e.stdout or "")[-2000:]
        logger.error("ascend-fd diag failed: %s", detail)
        raise _DiagError(
            f"Diagnosis error: ascend-fd failed to run the diagnosis, please check the relevant logs: {detail}"
        ) from e
    report = out_dir / "fault_diag_result" / "diag_report.json"
    data = json.loads(report.read_text(encoding="utf-8")) if report.exists() else {}
    return str(out_dir), data, report_text


# --------------------------------------------------------------------------- #
# Solidify the main flow: a deterministic skill that does not depend on the LLM.
# --------------------------------------------------------------------------- #
def diagnose(job: str, namespace: str = "default") -> dict:
    """End-to-end diagnosis of one job: relcache looks up the central relation table by jobname
    to get all pod->node mappings -> per-node collect + local cleanup -> assemble -> centralized diag.

    Returns {pods, collected, diag_input_dir, diag_output_dir, diag_report, error}.
    Purely deterministic, no LLM call.
    """
    from agent_core import relcache

    logger.info("diagnosis started: job=%s ns=%s", job, namespace)
    pods = relcache.lookup(job, namespace)
    if not pods:
        logger.warning("diagnosis failed: job=%s ns=%s no pods", job, namespace)
        return {
            "error": f"Diagnosis error: no diagnosable pod for task {job} (ns={namespace}), please confirm the task is running properly",
            "pods": [],
        }
    collected = dispatch_collect(job, pods)
    ok = [c for c in collected if c.get("ok")]
    if not ok:
        logger.warning("diagnosis failed: job=%s ns=%s no node collected successfully", job, namespace)
        return {
            "error": "Diagnosis error: all node collections failed, please check the agent-core and node-collector logs",
            "pods": pods,
            "collected": collected,
        }
    incomplete_nodes = [c.get("host_ip") or c["node"] for c in collected if not c.get("ok") and c.get("node")]
    # detect empty uploads before assemble_diag_input: it moves worker dirs into the diag input
    empty_nodes = [
        c.get("host_ip") or c["node"]
        for c in collected
        if c.get("ok") and c.get("worker_dir") and not _has_nonempty_file(c["worker_dir"])
    ]
    diag_input = assemble_diag_input(collected, job, namespace)
    if empty_nodes:
        logger.warning(
            "collect empty: job=%s nodes reported empty collection/parsed data: %s",
            job,
            ", ".join(empty_nodes),
        )
    notes_text = nodes_note(incomplete_nodes, empty_nodes)
    try:
        out_dir, report, report_text = run_diag(diag_input)
    except _DiagError as e:
        logger.error("diagnosis failed (ascend-fd diag): job=%s ns=%s err=%s", job, namespace, e)
        return {
            "pods": pods,
            "collected": collected,
            "diag_input_dir": diag_input,
            "diag_output_dir": None,
            "diag_report": {},
            "incomplete_nodes": incomplete_nodes,
            "empty_nodes": empty_nodes,
            "error": str(e),
        }
    logger.info(
        "diagnosis completed: job=%s ns=%s workers=%d report_keys=%s", job, namespace, len(ok), list(report)[:10]
    )
    return {
        "pods": pods,
        "collected": collected,
        "diag_input_dir": diag_input,
        "diag_output_dir": out_dir,
        "diag_report": report,
        "diag_report_text": (report_text + "\n\n" + notes_text).strip() if notes_text else report_text,
        "incomplete_nodes": incomplete_nodes,
        "empty_nodes": empty_nodes,
        "error": None,
    }


# --------------------------------------------------------------------------- #
# Repeat-diagnosis guard + result cache (mutex for concurrent runs of the same task;
# every successful diagnosis is cached; a cache hit prompts --refresh for real-time data)
# --------------------------------------------------------------------------- #
_active_lock = threading.Lock()
_active_diags: dict[tuple[str, str], float] = {}  # (ns, job) -> start_ts; mutex within the single-replica process
# Short-TTL in-memory recent-result cache: a repeated diagnosis of the same job within
# RECENT_TTL (default 10s) returns the latest outcome directly (marked as cached) without
# re-collecting; --refresh bypasses it. Independent of the persistent result cache.
_recent_results: dict[tuple[str, str], tuple[float, dict]] = {}  # (ns, job) -> (ts, result)
RECENT_TTL = float(os.environ.get("DIAG_RECENT_TTL", "10"))


def is_diag_active(job: str, namespace: str = "default") -> bool:
    """Return whether (namespace, job) is currently being diagnosed."""
    with _active_lock:
        return _active_diags.get((namespace, job)) is not None


def job_exists(job: str, namespace: str) -> bool:
    """Return whether the task is diagnosable: the relation cache still holds any of the
    job's pods (live, or deleted within the TTL whose logs remain on nodes / shared storage).

    relcache only records pods owned by the configured task CRs, so an empty lookup means
    the job name is wrong or all its pods are gone -> report "task not found" immediately.
    """
    from agent_core import relcache

    return len(relcache.lookup(job, namespace)) > 0


def _cache_file(job: str, namespace: str) -> Path:
    return _cache_root() / f"{namespace}_{job}.json"


def _read_diag_cache(job: str, namespace: str) -> dict | None:
    try:
        p = _cache_file(job, namespace)
        if not p.exists():
            return None
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def _write_diag_cache(job: str, namespace: str, result: dict) -> None:
    """Write the result cache; best-effort (a cache write failure must not fail the diagnosis)."""
    try:
        p = _cache_file(job, namespace)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(result, ensure_ascii=False, default=str), encoding="utf-8")
    except Exception as e:  # noqa: BLE001  # cache write is best-effort
        logger.warning("failed to write diag cache: job=%s ns=%s: %s", job, namespace, e)


def cache_diag_final_text(job: str, namespace: str, final_text: str) -> None:
    """Write the LLM summary (final_text) back into the stopped-task result cache, so a later
    cache hit returns the cached summary directly without re-calling the LLM.

    Best-effort: only touches an existing cache file (the task is stopped and cached); never raises.
    """
    try:
        p = _cache_file(job, namespace)
        if not p.exists():
            return
        data = json.loads(p.read_text(encoding="utf-8"))
        data["final_text"] = final_text
        p.write_text(json.dumps(data, ensure_ascii=False, default=str), encoding="utf-8")
    except Exception as e:  # noqa: BLE001  # summary cache writeback is best-effort
        logger.warning("failed to cache LLM summary for job=%s ns=%s: %s", job, namespace, e)


def diagnose_cached(job: str, namespace: str = "default", refresh: bool = False) -> dict:
    """End-to-end diagnosis entry with repeat-diagnosis guard + result cache.

    - Task not found: no relcache record for the job (wrong job name, or the task and
      its pods are gone) -> return "training/inference task not found" immediately,
      before any cached result is served.
    - Recent cache: same (ns, job) diagnosed within RECENT_TTL (default 10s) and not
      refresh -> return the latest outcome directly (marked as cached, with a hint to use
      --refresh for real-time data), no re-collect.
    - Guard: same (ns, job) already being diagnosed -> return an "already diagnosing"
      error, no re-run.
    - Cache: every successful diagnosis writes the persistent result cache (task running
      or stopped); a cache hit without refresh returns the cached result with a hint to
      use --refresh; refresh bypasses the cache, re-runs, then refreshes the cache.
    """
    key = (namespace, job)
    if not refresh:
        now = time.time()
        hit = _recent_results.get(key)
        if hit is not None and now - hit[0] < RECENT_TTL:
            logger.info("recent cache hit: job=%s ns=%s (within %ss)", job, namespace, RECENT_TTL)
            out = dict(hit[1])
            out["cached"] = True
            out["cached_note"] = "This is cached data; add --refresh for real-time data"
            return out
        # cheap sweep of expired recent entries
        for k in [k for k, (ts, _) in _recent_results.items() if now - ts >= RECENT_TTL]:
            _recent_results.pop(k, None)
    with _active_lock:
        if _active_diags.get(key) is not None:
            started = _active_diags[key]
            logger.warning("job=%s ns=%s already diagnosing, rejecting duplicate run", job, namespace)
            return {
                "error": f"job={job} is being diagnosed (started at "
                f"{time.strftime('%H:%M:%S', time.localtime(started))}), please do not run it again",
                "pods": [],
                "diag_report": {},
            }
        _active_diags[key] = time.time()
    try:
        # Task existence is the primary gate: no relcache record -> the task (or all its
        # pods) is gone; return "task not found" instead of serving a stale cached result.
        if not job_exists(job, namespace):
            logger.warning("task not found: job=%s ns=%s", job, namespace)
            return {
                "error": f"Training/inference task not found: job={job} in ns={namespace}",
                "pods": [],
                "diag_report": {},
            }
        if not refresh:
            cached = _read_diag_cache(job, namespace)
            if cached is not None:
                logger.info("cache hit: job=%s ns=%s", job, namespace)
                cached["cached"] = True
                cached["cached_note"] = "Result from cache; run --refresh for the latest diagnosis"
                return cached
        logger.info("starting diagnosis: job=%s ns=%s refresh=%s", job, namespace, refresh)
        result = diagnose(job, namespace)
        _recent_results[key] = (time.time(), result)  # remember the latest outcome for the recent cache
        if not result.get("error"):
            snapshot = {
                "pods": result.get("pods"),
                "diag_report": result.get("diag_report"),
                "diag_report_text": result.get("diag_report_text"),
                "incomplete_nodes": result.get("incomplete_nodes", []),
                "empty_nodes": result.get("empty_nodes", []),
                "error": result.get("error"),
                "cached_at": time.time(),
                "cached": False,
            }
            _write_diag_cache(job, namespace, snapshot)
            logger.info("diagnosis completed, result cached: job=%s ns=%s", job, namespace)
        return result
    except Exception as e:  # noqa: BLE001  # never let an unexpected failure escape as a 500; surface a readable reason
        logger.exception("diagnosis crashed: job=%s ns=%s", job, namespace)
        return {
            "error": f"Diagnosis error: an exception occurred during diagnosis, please check the agent-core logs ({e})",
            "pods": [],
            "diag_report": {},
        }
    finally:
        with _active_lock:
            _active_diags.pop(key, None)
        # Enforce the workspace quota after each diagnosis so artifacts + cache never grow unbounded.
        quota.enforce_quota(WORK_ROOT, cache_dir=_cache_root())
