#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Diagnosis agent toolset.

The central relation cache (agent.relcache) maintains task→pod→{node,poduid,rank}
and is queried directly by jobname; mount paths are resolved by the collector's
local pathmap and do not go through the agent.

diagnose(job, namespace): relcache.lookup -> all pod->node -> concurrently issue
TriggerCollect to each node (short-lived connection returns immediately) -> each
node's collector collects + cleans in the background, then actively reports via
UploadResult -> the agent aggregates with JobTracker, and after all arrive / timeout
-> assemble -> ascend-fd diag. Async model: no long-lived connections even with
500 nodes; collection takes ~10 min/node and can run in parallel.
Deterministic, no LLM dependency; report summarization is done by the caller
(agent.py / HTTP layer) as needed.
"""

# pylint: disable=no-member  # diag_pb2 members are dynamically generated by the protobuf builder, invisible to static analysis

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import grpc
import yaml
from kubernetes import client

from agent_core.constants import TASK_CRDS_CM_KEY, TASK_CRDS_CM_NAME, TASK_CRDS_CM_NS, WORK_ROOT
from agent_core.jobs import tracker
from agent_core.k8s import K8s
from clusterops_common import quota
from diagproto import diag_pb2, diag_pb2_grpc

logger = logging.getLogger(__name__)

COLLECTOR_PORT = int(os.environ.get("COLLECTOR_PORT", "9720"))
ASCEND_FD = os.environ.get("ASCEND_FD_BIN", "ascend-fd")
COLLECT_TIMEOUT = float(
    os.environ.get("COLLECT_TIMEOUT", "600")
)  # 10 min: start diag at deadline, ignore nodes that did not upload
TRIGGER_TIMEOUT = float(os.environ.get("TRIGGER_TIMEOUT", "30"))  # TriggerCollect only confirms receipt


def _cache_root() -> Path:
    """Result cache directory: {WORK_ROOT}/cache (AGENT_CACHE_DIR overrides)."""
    override = os.environ.get("AGENT_CACHE_DIR")
    if override:
        return Path(override)
    return WORK_ROOT / "cache"


# --------------------------------------------------------------------------- #
# k8s (K8s.core() / K8s.namespace() from agent_core.k8s)
# --------------------------------------------------------------------------- #
def _collector_pod_ip(v1, node: str) -> str | None:
    """Find the IP of the collector DaemonSet pod running on the given node."""
    pods = v1.list_pod_for_all_namespaces(label_selector="app=node-collector")
    for p in pods.items:
        if p.spec.node_name == node and p.status.pod_ip:
            return p.status.pod_ip
    return None


# --------------------------------------------------------------------------- #
# collect dispatch (gRPC)
# --------------------------------------------------------------------------- #
def _trigger_node(v1, node: str, job: str, refs: list[dict]) -> dict:
    """TriggerCollect a single node (short-lived connection returns immediately); a failed trigger is recorded as the final failure."""
    pod_ip = _collector_pod_ip(v1, node)
    if not pod_ip:
        return {
            "node": node,
            "ok": False,
            "error": f"no collector pod on node {node}",
            "artifacts_tar": None,
            "worker_dir": None,
        }
    addr = f"{pod_ip}:{COLLECTOR_PORT}"
    req = diag_pb2.CollectRequest(
        node=node,
        job=job,
        pods=[diag_pb2.PodRef(ns=p.get("ns", "default"), name=p["name"], pod_uid=p["pod_uid"]) for p in refs],
    )
    try:
        with grpc.insecure_channel(addr) as ch:
            ack = diag_pb2_grpc.CollectorStub(ch).TriggerCollect(req, timeout=TRIGGER_TIMEOUT)
        if not ack.accepted:
            return {
                "node": node,
                "ok": False,
                "error": f"trigger rejected: {ack.message}",
                "artifacts_tar": None,
                "worker_dir": None,
            }
        return {"node": node, "ok": True, "error": None, "artifacts_tar": None, "worker_dir": None}
    except grpc.RpcError as e:
        detail = e.details() or e.code().name
        return {
            "node": node,
            "ok": False,
            "error": f"grpc trigger failed: {detail}",
            "artifacts_tar": None,
            "worker_dir": None,
        }


def _newer_pod(a: dict, b: dict) -> bool:
    """True if pod entry a is newer than b: a live pod beats a deleted one, otherwise later deleted_at wins."""
    if bool(a.get("deleted_at")) != bool(b.get("deleted_at")):
        return not a.get("deleted_at")  # the live (not deleted) one is newer
    return bool(a.get("deleted_at")) and a["deleted_at"] >= b["deleted_at"]


def _group_by_node(pods: list[dict]) -> dict[str, list[dict]]:
    """Group pods by node; issue once per node carrying all its pods (pod_uid/ns/name).

    host_paths are not sent: resolved by the collector's local pathmap (RFC §3.3.5).
    Pods sharing the same (node, name) are the same logical pod rescheduled on the
    same node: keep only the latest instance (_newer_pod).
    """
    latest: dict[tuple[str, str], dict] = {}  # (node, name) -> newest pod entry
    for p in pods:
        node = p.get("node")
        if not node:
            continue
        key = (node, p.get("pod_name"))
        cur = latest.get(key)
        if cur is None or _newer_pod(p, cur):
            latest[key] = p
    by_node: dict[str, list[dict]] = {}
    for (node, _name), p in latest.items():
        by_node.setdefault(node, []).append(
            {
                "pod_uid": p["pod_uid"],
                "ns": p.get("namespace", "default") or "default",
                "name": p["pod_name"],
            }
        )
    return by_node


def dispatch_collect(job: str, pods: list[dict]) -> list[dict]:
    """Dispatch asynchronously: group -> concurrent TriggerCollect (short-lived) -> JobTracker aggregates reported results.

    Nodes that fail to trigger or time out without reporting are filled in as ok=False,
    so the caller's barrier always gets a complete result.
    Returns [node->result] aligned with the node order.
    """
    by_node = _group_by_node(pods)
    nodes = list(by_node)
    if not nodes:
        logger.warning("job=%s has no valid nodes (pods not scheduled / no node)", job)
        return []
    v1 = K8s.core()
    logger.info("dispatching collect: job=%s nodes=%d pods=%d", job, len(nodes), len(pods))
    tracker.register(job, nodes)
    # The 10-min timeout starts when the collect request is sent: start diag at deadline, ignore nodes not uploaded.
    deadline = time.monotonic() + COLLECT_TIMEOUT

    def trigger(node: str) -> None:
        res = _trigger_node(v1, node, job, by_node[node])
        if not res["ok"]:  # trigger failed immediately: record the final result, stop waiting for upload
            tracker.complete(job, node, res)

    with ThreadPoolExecutor(max_workers=min(64, len(nodes))) as ex:
        list(ex.map(trigger, nodes))

    results = tracker.wait(job, timeout=max(0.0, deadline - time.monotonic()))
    for node in nodes:
        if node not in results:  # timed out without upload
            tracker.complete(
                job,
                node,
                {
                    "node": node,
                    "ok": False,
                    "error": "collect timeout (no upload)",
                    "artifacts_tar": None,
                    "worker_dir": None,
                },
            )
    final = tracker.get(job)
    results = final["results"] if final else {}
    ok_nodes = [n for n in nodes if results.get(n, {}).get("ok")]
    logger.info("collect result aggregated: job=%s ok=%d/%d", job, len(ok_nodes), len(nodes))
    return [results.get(n) for n in nodes]


# --------------------------------------------------------------------------- #
# Assemble the diag input directory
# --------------------------------------------------------------------------- #
def assemble_diag_input(collected: list[dict], job: str, namespace: str) -> str:
    """Assemble diag input dir per ascend-fd diag 'multi-worker dump' contract.

    Layout: {WORK_ROOT}/{YYYYMMDD}/{namespace}_{job}/diag-input/worker{idx}/
    (idx = 0..N-1 in the order of successful collected nodes). Uploads are extracted
    straight into diag-input/worker-<node>/ (see upload.py); here they are
    renamed to workerN. Each worker subdir must contain server-info.json; ascend-fd
    uses the subdir name as the worker name shown in the report (worker0, worker1, ...).
    """
    ns_job = f"{namespace}_{job}"
    diag_input = WORK_ROOT / time.strftime("%Y%m%d") / ns_job / "diag-input"
    diag_input.mkdir(parents=True, exist_ok=True)
    # clean stale workerN dirs, keep current worker-<node> staging
    for p in diag_input.iterdir():
        if p.is_dir() and p.name.startswith("worker") and not p.name.startswith("worker-"):
            shutil.rmtree(p, ignore_errors=True)
    worker_idx = 0
    for r in collected:
        if not r["ok"] or not r["worker_dir"]:
            continue
        src = Path(r["worker_dir"])
        dst = diag_input / f"worker{worker_idx}"
        if src.is_dir():
            shutil.rmtree(dst, ignore_errors=True)
            shutil.move(str(src), str(dst))
        worker_idx += 1
    return str(diag_input)


# --------------------------------------------------------------------------- #
# Diagnosis (skill: call the ascend-fd diag CLI)
# --------------------------------------------------------------------------- #
class _DiagError(Exception):
    """ascend-fd diag failed (carries a CLI stderr summary); turned into a readable error by diagnose."""


def run_diag(diag_input_dir: str) -> tuple[str, dict]:
    """Run `ascend-fd diag -i <diag_input> -o <out>`, return (out_dir, diag_report).

    The output goes to the sibling {WORK_ROOT}/{YYYYMMDD}/{ns}_{job}/diag-output of the
    input (diag_input = .../{ns}_{job}/diag-input, so one level up); on failure
    raise _DiagError carrying a stderr summary instead of a raw CalledProcessError.
    """
    out_dir = Path(diag_input_dir).parent / "diag-output"
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [ASCEND_FD, "diag", "-i", diag_input_dir, "-o", str(out_dir)]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=1800)
    except subprocess.TimeoutExpired as e:
        logger.error("ascend-fd diag timed out: %s", e)
        raise _DiagError("诊断错误，ascend-fd 诊断超时，请查看对应日志或稍后重试") from e
    except subprocess.CalledProcessError as e:
        detail = (e.stderr or e.stdout or "")[-2000:]
        logger.error("ascend-fd diag failed: %s", detail)
        raise _DiagError(f"诊断错误，ascend-fd 执行诊断失败，请查看对应日志: {detail}") from e
    report = out_dir / "fault_diag_result" / "diag_report.json"
    data = json.loads(report.read_text(encoding="utf-8")) if report.exists() else {}
    return str(out_dir), data


# --------------------------------------------------------------------------- #
# Solidify the main flow: a deterministic skill that does not depend on the LLM.
# --------------------------------------------------------------------------- #
def diagnose(job: str, namespace: str = "default") -> dict:
    """End-to-end diagnosis of one job: relcache looks up the central relation table by jobname
    to get all pod->node mappings -> per-node collect + local cleanup -> assemble -> centralized diag.

    Returns {pods, collected, diag_input_dir, diag_output_dir, diag_report, error}.
    Purely deterministic, no LLM call.
    """
    from agent_core import relcache

    logger.info("diagnosis started: job=%s ns=%s", job, namespace)
    pods = relcache.lookup(job, namespace)
    if not pods:
        logger.warning("diagnosis failed: job=%s ns=%s no pods", job, namespace)
        return {"error": f"诊断错误，任务 {job} 没有可诊断的 pod (ns={namespace})，请确认任务已正常拉起", "pods": []}
    collected = dispatch_collect(job, pods)
    ok = [c for c in collected if c.get("ok")]
    if not ok:
        logger.warning("diagnosis failed: job=%s ns=%s no node collected successfully", job, namespace)
        return {
            "error": "诊断错误，节点采集全部失败，请查看 agent-core 与 node-collector 日志",
            "pods": pods,
            "collected": collected,
        }
    diag_input = assemble_diag_input(collected, job, namespace)
    try:
        out_dir, report = run_diag(diag_input)
    except _DiagError as e:
        logger.error("diagnosis failed (ascend-fd diag): job=%s ns=%s err=%s", job, namespace, e)
        return {
            "pods": pods,
            "collected": collected,
            "diag_input_dir": diag_input,
            "diag_output_dir": None,
            "diag_report": {},
            "error": str(e),
        }
    logger.info(
        "diagnosis completed: job=%s ns=%s workers=%d report_keys=%s", job, namespace, len(ok), list(report)[:10]
    )
    return {
        "pods": pods,
        "collected": collected,
        "diag_input_dir": diag_input,
        "diag_output_dir": out_dir,
        "diag_report": report,
        "error": None,
    }


# --------------------------------------------------------------------------- #
# Repeat-diagnosis guard + result cache (mutex for concurrent runs of the same task; only stopped tasks are cached)
# --------------------------------------------------------------------------- #
_active_lock = threading.Lock()
_active_diags: dict[tuple[str, str], float] = {}  # (ns, job) -> start_ts; mutex within the single-replica process
# Short-TTL in-memory recent-result cache: a repeated diagnosis of the same job within
# RECENT_TTL (default 10s) returns the latest outcome directly (marked as cached) without
# re-collecting; --refresh bypasses it. Independent of the persistent stopped-task cache.
_recent_results: dict[tuple[str, str], tuple[float, dict]] = {}  # (ns, job) -> (ts, result)
RECENT_TTL = float(os.environ.get("DIAG_RECENT_TTL", "10"))


def is_diag_active(job: str, namespace: str = "default") -> bool:
    """Return whether (namespace, job) is currently being diagnosed."""
    with _active_lock:
        return _active_diags.get((namespace, job)) is not None


_task_crds_cache: list[tuple[str, str, str]] | None = None


def _load_task_crds() -> list[tuple[str, str, str]]:
    """Read task CR config CM via the K8s API -> [(group, version, kind)] list (same source as relcache).

    Read once and cached for the process lifetime.
    """
    global _task_crds_cache
    if _task_crds_cache is not None:
        return _task_crds_cache
    try:
        v1 = K8s.core()
        cm = v1.read_namespaced_config_map(TASK_CRDS_CM_NAME, TASK_CRDS_CM_NS)
        cfg = yaml.safe_load((cm.data or {}).get(TASK_CRDS_CM_KEY, "")) or {}
    except Exception:  # noqa: BLE001  # config read failed -> no task CR, job_exists/task_state handled conservatively
        return []  # not cached, retried on the next call
    out: list[tuple[str, str, str]] = []
    for e in cfg.get("task_crds") or []:
        kind = e.get("kind")
        if not kind:
            continue
        av = (e.get("api_version", "") or "").strip()
        group, sep, version = av.rpartition("/")
        if not sep:
            group, version = "", av  # core group (task CRs are usually custom groups; fallback handling)
        out.append((group, version, kind))
    _task_crds_cache = out
    return out


def _cr_plural(kind: str) -> str:
    """Simple pluralization rule for resources: AscendJob -> ascendjobs, InferServiceSet -> inferservicesets."""
    if kind.endswith("y"):
        return kind[:-1].lower() + "ies"
    return kind.lower() + "s"


def job_exists(job: str, namespace: str) -> bool:
    """Return whether the task CR exists (not found means the task does not exist; short-circuits wrong user input).

    A failed CR query (RBAC/network etc.) is treated as existing to avoid a false
    "task not found" blocking normal diagnosis. Multiple task CR types (e.g.
    AscendJob + Volcano Job) are probed in order; any hit means it exists; only when
    all types return 404 is the task considered non-existent.
    """
    K8s.core()  # load in-cluster/kubeconfig config so CustomObjectsApi works
    custom = client.CustomObjectsApi()
    crds = _load_task_crds()
    if not crds:
        return True  # no task CR config -> treat as existing, avoid false negative
    for group, version, kind in crds:
        try:
            custom.get_namespaced_custom_object(
                group=group, version=version, namespace=namespace, plural=_cr_plural(kind), name=job
            )
            return True
        except client.exceptions.ApiException as e:
            if e.status == 404:
                continue  # this kind has no such task -> try the next kind
            return True  # query for this kind failed (RBAC/network etc.) -> treat as existing, avoid false negative
        except Exception:
            return True
    return False  # all configured kinds returned 404 -> task does not exist


# Terminal condition types across task CR families (matched case-insensitively):
# AscendJob: JobSucceeded/JobFailed; batch Job: Complete/Failed; Volcano Job:
# Completed/Terminated/Aborted/Failed; plus generic Succeeded/Failed/Stopped aliases.
_TERMINAL_CONDITION_TYPES = frozenset(
    t.lower()
    for t in (
        "JobSucceeded",
        "JobFailed",
        "Succeeded",
        "Failed",
        "Stopped",
        "Complete",
        "Completed",
        "Terminated",
        "Aborted",
    )
)


def task_state(job: str, namespace: str) -> str:
    """Determine run state from the task CR status; returns running / stopped / unknown.

    stopped: conditions contain a terminal state with status=True (type matched
    case-insensitively, covering JobSucceeded/JobFailed/Succeeded/Failed/Stopped/
    Complete(d)/Terminated/Aborted across AscendJob / batch Job / Volcano Job);
    task CR missing (404, deleted) -> stopped (logs no longer change, cacheable);
    query failure (RBAC/network etc.) -> unknown (does not block diagnosis, skips cache).
    """
    K8s.core()  # load in-cluster/kubeconfig config so CustomObjectsApi works
    custom = client.CustomObjectsApi()
    crds = _load_task_crds()
    if not crds:
        return "unknown"
    for group, version, kind in crds:
        try:
            obj = custom.get_namespaced_custom_object_status(
                group=group, version=version, namespace=namespace, plural=_cr_plural(kind), name=job
            )
        except client.exceptions.ApiException as e:
            if e.status == 404:
                continue  # this kind has no such task -> try the next kind
            return "unknown"  # query failed (RBAC/network etc.) -> cannot determine, skip cache
        except Exception:
            return "unknown"
        for c in (obj.get("status") or {}).get("conditions") or []:
            if (
                str(c.get("status") or "").lower() == "true"
                and str(c.get("type") or "").lower() in _TERMINAL_CONDITION_TYPES
            ):
                return "stopped"
        return "running"
    return "stopped"  # all kinds returned 404 -> task deleted, logs no longer change, cacheable


def _cache_file(job: str, namespace: str) -> Path:
    return _cache_root() / f"{namespace}_{job}.json"


def _read_diag_cache(job: str, namespace: str) -> dict | None:
    try:
        p = _cache_file(job, namespace)
        if not p.exists():
            return None
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def _write_diag_cache(job: str, namespace: str, result: dict) -> None:
    p = _cache_file(job, namespace)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(result, ensure_ascii=False, default=str), encoding="utf-8")


def cache_diag_final_text(job: str, namespace: str, final_text: str) -> None:
    """Write the LLM summary (final_text) back into the stopped-task result cache, so a later
    cache hit returns the cached summary directly without re-calling the LLM.

    Best-effort: only touches an existing cache file (the task is stopped and cached); never raises.
    """
    try:
        p = _cache_file(job, namespace)
        if not p.exists():
            return
        data = json.loads(p.read_text(encoding="utf-8"))
        data["final_text"] = final_text
        p.write_text(json.dumps(data, ensure_ascii=False, default=str), encoding="utf-8")
    except Exception as e:  # noqa: BLE001  # summary cache writeback is best-effort
        logger.warning("failed to cache LLM summary for job=%s ns=%s: %s", job, namespace, e)


def _task_effectively_stopped(job: str, namespace: str) -> bool:
    """Cacheability check: is the task's result stable enough to cache?

    True when the task CR status is stopped, or (when the CR status cannot be read,
    e.g. missing RBAC / network, or lags) all the task's pods have reached a terminal
    phase (Succeeded/Failed, matched case-insensitively) per the relcache — their logs
    no longer change.
    """
    if task_state(job, namespace) == "stopped":
        return True
    from agent_core import relcache

    pods = relcache.lookup(job, namespace)
    return bool(pods) and all((p.get("phase") or "").lower() in ("succeeded", "failed") for p in pods)


def diagnose_cached(job: str, namespace: str = "default", refresh: bool = False) -> dict:
    """End-to-end diagnosis entry with repeat-diagnosis guard + result cache.

    - Recent cache: same (ns, job) diagnosed within RECENT_TTL (default 10s) and not
      refresh -> return the latest outcome directly (marked as cached, with a hint to use
      --refresh for real-time data), no re-collect.
    - Guard: same (ns, job) already being diagnosed -> return an "already diagnosing"
      error, no re-run.
    - Task not found: task CR not found (wrong job name) -> return "training/inference
      task not found", no collection.
    - Cache: task stopped + cache exists and not refresh -> return the cache directly
      (no collect/diagnose); otherwise re-run; after a successful diagnosis the cache is
      written only when the task is stopped, running tasks are not cached.
    """
    key = (namespace, job)
    if not refresh:
        now = time.time()
        hit = _recent_results.get(key)
        if hit is not None and now - hit[0] < RECENT_TTL:
            logger.info("recent cache hit: job=%s ns=%s (within %ss)", job, namespace, RECENT_TTL)
            out = dict(hit[1])
            out["cached"] = True
            out["cached_note"] = "这是缓存数据，需要实时数据，请加 --refresh"
            return out
        # cheap sweep of expired recent entries
        for k in [k for k, (ts, _) in _recent_results.items() if now - ts >= RECENT_TTL]:
            _recent_results.pop(k, None)
    with _active_lock:
        if _active_diags.get(key) is not None:
            started = _active_diags[key]
            logger.warning("job=%s ns=%s already diagnosing, rejecting duplicate run", job, namespace)
            return {
                "error": f"job={job} 正在诊断中(开始于 "
                f"{time.strftime('%H:%M:%S', time.localtime(started))}), 请勿重复执行",
                "pods": [],
                "diag_report": {},
            }
        _active_diags[key] = time.time()
    try:
        if not refresh:
            cached = _read_diag_cache(job, namespace)
            if cached is not None and _task_effectively_stopped(job, namespace):
                logger.info("cache hit: job=%s ns=%s (task stopped)", job, namespace)
                cached["cached"] = True
                return cached
        if not job_exists(job, namespace):
            logger.warning("task not found: job=%s ns=%s", job, namespace)
            return {
                "error": f"训练/推理任务不存在: job={job} in ns={namespace}",
                "pods": [],
                "diag_report": {},
            }
        logger.info("starting diagnosis: job=%s ns=%s refresh=%s", job, namespace, refresh)
        result = diagnose(job, namespace)
        _recent_results[key] = (time.time(), result)  # remember the latest outcome for the recent cache
        if not result.get("error") and _task_effectively_stopped(job, namespace):
            snapshot = {
                "pods": result.get("pods"),
                "diag_report": result.get("diag_report"),
                "error": result.get("error"),
                "cached_at": time.time(),
                "task_state": "stopped",
                "cached": False,
            }
            _write_diag_cache(job, namespace, snapshot)
            logger.info("diagnosis completed and task stopped, result cached: job=%s ns=%s", job, namespace)
        return result
    except Exception as e:  # noqa: BLE001  # never let an unexpected failure escape as a 500; surface a readable reason
        logger.exception("diagnosis crashed: job=%s ns=%s", job, namespace)
        return {"error": f"诊断错误，诊断过程发生异常，请查看 agent-core 日志 ({e})", "pods": [], "diag_report": {}}
    finally:
        with _active_lock:
            _active_diags.pop(key, None)
        # Enforce the workspace quota after each diagnosis so artifacts + cache never grow unbounded.
        quota.enforce_quota(WORK_ROOT, cache_dir=_cache_root())
