#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Agent-side upload service: receives collection results reported by node-collector (gRPC Uploader, :9710).

The first chunk of the upload stream carries node/job/namespace/ok/error plus the first data chunk;
subsequent chunks carry only data. On success: the tar.gz is stored and extracted straight into
diag-input under <WORK_ROOT>/{YYYYMMDD}/{ns}_{job}/; on failure: only the result is recorded,
nothing is written to disk.
"""

# pylint: disable=no-member  # diag_pb2 members are dynamically generated by the protobuf builder, invisible to static checks

from __future__ import annotations

import logging
import os
import shutil
import tarfile
import time
from concurrent.futures import ThreadPoolExecutor

import grpc

from agent_core.constants import WORK_ROOT
from agent_core.jobs import tracker
from agent_core.tools import is_diag_active
from diagproto import diag_pb2, diag_pb2_grpc

logger = logging.getLogger(__name__)

# Upload storage layout (root dir from agent_core.constants.WORK_ROOT):
#   {ROOT}/{YYYYMMDD}/{ns}_{job}/parse-result-{job}-{node}.tar.gz   collected tar archive (per uploader node)
#   {ROOT}/{YYYYMMDD}/{ns}_{job}/diag-input/worker-{node}/   extracted clean artifacts (per node; assemble renames to workerN)
UPLOAD_PORT = int(os.environ.get("AGENT_GRPC_PORT", "9710"))
_MAX_WORKERS = int(os.environ.get("AGENT_UPLOAD_WORKERS", "32"))


def _result(
    node: str, ok: bool, error: str | None = None, artifacts_tar: str | None = None, worker_dir: str | None = None
) -> dict:
    return {"node": node, "ok": ok, "error": error, "artifacts_tar": artifacts_tar, "worker_dir": worker_dir}


class UploaderServicer(diag_pb2_grpc.UploaderServicer):
    """Accept collector client-streaming uploads and update the JobTracker in real time."""

    def UploadResult(self, request_iterator, context):  # noqa: N802
        try:
            first = next(request_iterator)
        except StopIteration:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "empty upload stream")
            return diag_pb2.UploadAck(received=False)

        ns = first.namespace or "default"
        if not is_diag_active(first.job, ns):
            logger.warning("reject upload: job=%s ns=%s node=%s not being diagnosed", first.job, ns, first.node)
            context.abort(grpc.StatusCode.PERMISSION_DENIED, f"job={first.job} is not being diagnosed")
            return diag_pb2.UploadAck(received=False)

        if not first.ok:
            logger.warning("upload failed: job=%s node=%s error=%s", first.job, first.node, first.error)
            tracker.complete(first.job, first.node, _result(first.node, False, error=first.error or "collect failed"))
            return diag_pb2.UploadAck(received=True)

        day_dir = WORK_ROOT / time.strftime("%Y%m%d")
        day_dir.mkdir(parents=True, exist_ok=True)
        job_dir = day_dir / f"{ns}_{first.job}"
        job_dir.mkdir(parents=True, exist_ok=True)
        tar_path = job_dir / f"parse-result-{first.job}-{first.node}.tar.gz"  # archive: per uploader node, no collision
        worker_dir = (
            job_dir / "diag-input" / f"worker-{first.node}"
        )  # extract straight into diag-input; assemble renames to workerN
        try:
            with tar_path.open("wb") as f:
                if first.data:
                    f.write(first.data)
                for chunk in request_iterator:
                    f.write(chunk.data)
            shutil.rmtree(worker_dir, ignore_errors=True)
            worker_dir.mkdir(parents=True, exist_ok=True)
            with tarfile.open(tar_path, mode="r:gz") as tf:
                # Reject path-traversal, symlink, and device members in untrusted uploads.
                tf.extractall(worker_dir, filter="data")
            logger.info("upload succeeded and stored: job=%s node=%s tar=%s", first.job, first.node, tar_path)
            tracker.complete(
                first.job,
                first.node,
                _result(first.node, True, artifacts_tar=str(tar_path), worker_dir=str(worker_dir)),
            )
        except Exception as e:  # noqa: BLE001
            logger.exception("failed to store upload: job=%s node=%s", first.job, first.node)
            context.abort(grpc.StatusCode.INTERNAL, f"upload store failed: {e}")
            return diag_pb2.UploadAck(received=False)
        return diag_pb2.UploadAck(received=True)


def start_upload_server(port: int = UPLOAD_PORT) -> grpc.Server:
    """Start the upload gRPC service (non-blocking; the server runs in background threads)."""
    # Pre-create the upload root directory at process startup.
    WORK_ROOT.mkdir(parents=True, exist_ok=True)
    server = grpc.server(ThreadPoolExecutor(max_workers=_MAX_WORKERS))
    diag_pb2_grpc.add_UploaderServicer_to_server(UploaderServicer(), server)
    server.add_insecure_port(f"0.0.0.0:{port}")
    server.start()
    logger.info("upload gRPC service started: :%s (work_root=%s)", port, WORK_ROOT)
    return server
