// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: container.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ContainerService_SyncData_FullMethodName            = "/ContainerService/SyncData"
	ContainerService_Coordinate_FullMethodName          = "/ContainerService/Coordinate"
	ContainerService_InitBroadcastStream_FullMethodName = "/ContainerService/InitBroadcastStream"
)

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerServiceClient interface {
	// Data sync (regular node -> leader)
	SyncData(ctx context.Context, in *SyncDataReq, opts ...grpc.CallOption) (*Response, error)
	// Coordinate request (faulty node -> leader; synchronously waits for broadcast responses from all nodes)
	Coordinate(ctx context.Context, in *CoordinateReq, opts ...grpc.CallOption) (*Response, error)
	// Establish a broadcast stream (regular node -> leader, bidirectional stream)
	// The node initiates the stream; the leader pushes CoordinateReq over it, and the node returns Response over it
	InitBroadcastStream(ctx context.Context, opts ...grpc.CallOption) (ContainerService_InitBroadcastStreamClient, error)
}

type containerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) SyncData(ctx context.Context, in *SyncDataReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, ContainerService_SyncData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) Coordinate(ctx context.Context, in *CoordinateReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, ContainerService_Coordinate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) InitBroadcastStream(ctx context.Context, opts ...grpc.CallOption) (ContainerService_InitBroadcastStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContainerService_ServiceDesc.Streams[0], ContainerService_InitBroadcastStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &containerServiceInitBroadcastStreamClient{stream}
	return x, nil
}

type ContainerService_InitBroadcastStreamClient interface {
	Send(*Response) error
	Recv() (*CoordinateReq, error)
	grpc.ClientStream
}

type containerServiceInitBroadcastStreamClient struct {
	grpc.ClientStream
}

func (x *containerServiceInitBroadcastStreamClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *containerServiceInitBroadcastStreamClient) Recv() (*CoordinateReq, error) {
	m := new(CoordinateReq)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContainerServiceServer is the server API for ContainerService service.
// All implementations must embed UnimplementedContainerServiceServer
// for forward compatibility
type ContainerServiceServer interface {
	// Data sync (regular node -> leader)
	SyncData(context.Context, *SyncDataReq) (*Response, error)
	// Coordinate request (faulty node -> leader; synchronously waits for broadcast responses from all nodes)
	Coordinate(context.Context, *CoordinateReq) (*Response, error)
	// Establish a broadcast stream (regular node -> leader, bidirectional stream)
	// The node initiates the stream; the leader pushes CoordinateReq over it, and the node returns Response over it
	InitBroadcastStream(ContainerService_InitBroadcastStreamServer) error
	mustEmbedUnimplementedContainerServiceServer()
}

// UnimplementedContainerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContainerServiceServer struct {
}

func (UnimplementedContainerServiceServer) SyncData(context.Context, *SyncDataReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (UnimplementedContainerServiceServer) Coordinate(context.Context, *CoordinateReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coordinate not implemented")
}
func (UnimplementedContainerServiceServer) InitBroadcastStream(ContainerService_InitBroadcastStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InitBroadcastStream not implemented")
}
func (UnimplementedContainerServiceServer) mustEmbedUnimplementedContainerServiceServer() {}

// UnsafeContainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServiceServer will
// result in compilation errors.
type UnsafeContainerServiceServer interface {
	mustEmbedUnimplementedContainerServiceServer()
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	s.RegisterService(&ContainerService_ServiceDesc, srv)
}

func _ContainerService_SyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).SyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_SyncData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).SyncData(ctx, req.(*SyncDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_Coordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).Coordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_Coordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).Coordinate(ctx, req.(*CoordinateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_InitBroadcastStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerServiceServer).InitBroadcastStream(&containerServiceInitBroadcastStreamServer{stream})
}

type ContainerService_InitBroadcastStreamServer interface {
	Send(*CoordinateReq) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type containerServiceInitBroadcastStreamServer struct {
	grpc.ServerStream
}

func (x *containerServiceInitBroadcastStreamServer) Send(m *CoordinateReq) error {
	return x.ServerStream.SendMsg(m)
}

func (x *containerServiceInitBroadcastStreamServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContainerService_ServiceDesc is the grpc.ServiceDesc for ContainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ContainerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncData",
			Handler:    _ContainerService_SyncData_Handler,
		},
		{
			MethodName: "Coordinate",
			Handler:    _ContainerService_Coordinate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitBroadcastStream",
			Handler:       _ContainerService_InitBroadcastStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "container.proto",
}
