// Code generated by protoc-gen-go. DO NOT EDIT.
// source: container.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Simple container info (reported only by distributed task containers)
type ContainerInfo struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PhyIds               []int32  `protobuf:"varint,3,rep,packed,name=phy_ids,json=phyIds,proto3" json:"phy_ids,omitempty"`
	JobId                string   `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobReplica           int32    `protobuf:"varint,5,opt,name=job_replica,json=jobReplica,proto3" json:"job_replica,omitempty"`
	EnableRecover        bool     `protobuf:"varint,6,opt,name=enable_recover,json=enableRecover,proto3" json:"enable_recover,omitempty"`
	PausedByPeer         string   `protobuf:"bytes,7,opt,name=paused_by_peer,json=pausedByPeer,proto3" json:"paused_by_peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerInfo) Reset()         { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()    {}
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afe31759757e49a, []int{0}
}

func (m *ContainerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerInfo.Unmarshal(m, b)
}
func (m *ContainerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerInfo.Marshal(b, m, deterministic)
}
func (m *ContainerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerInfo.Merge(m, src)
}
func (m *ContainerInfo) XXX_Size() int {
	return xxx_messageInfo_ContainerInfo.Size(m)
}
func (m *ContainerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerInfo proto.InternalMessageInfo

func (m *ContainerInfo) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContainerInfo) GetPhyIds() []int32 {
	if m != nil {
		return m.PhyIds
	}
	return nil
}

func (m *ContainerInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ContainerInfo) GetJobReplica() int32 {
	if m != nil {
		return m.JobReplica
	}
	return 0
}

func (m *ContainerInfo) GetEnableRecover() bool {
	if m != nil {
		return m.EnableRecover
	}
	return false
}

func (m *ContainerInfo) GetPausedByPeer() string {
	if m != nil {
		return m.PausedByPeer
	}
	return ""
}

// Data sync request (regular node -> leader)
type SyncDataReq struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NodeId               string           `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Containers           []*ContainerInfo `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	SyncTime             int64            `protobuf:"varint,4,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SyncDataReq) Reset()         { *m = SyncDataReq{} }
func (m *SyncDataReq) String() string { return proto.CompactTextString(m) }
func (*SyncDataReq) ProtoMessage()    {}
func (*SyncDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afe31759757e49a, []int{1}
}

func (m *SyncDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncDataReq.Unmarshal(m, b)
}
func (m *SyncDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncDataReq.Marshal(b, m, deterministic)
}
func (m *SyncDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncDataReq.Merge(m, src)
}
func (m *SyncDataReq) XXX_Size() int {
	return xxx_messageInfo_SyncDataReq.Size(m)
}
func (m *SyncDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncDataReq proto.InternalMessageInfo

func (m *SyncDataReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SyncDataReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SyncDataReq) GetContainers() []*ContainerInfo {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *SyncDataReq) GetSyncTime() int64 {
	if m != nil {
		return m.SyncTime
	}
	return 0
}

// Coordinate request (faulty node -> leader; also used for broadcast push)
type CoordinateReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobIds               []string `protobuf:"bytes,3,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	CtrIds               []string `protobuf:"bytes,4,rep,name=ctr_ids,json=ctrIds,proto3" json:"ctr_ids,omitempty"`
	Action               string   `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoordinateReq) Reset()         { *m = CoordinateReq{} }
func (m *CoordinateReq) String() string { return proto.CompactTextString(m) }
func (*CoordinateReq) ProtoMessage()    {}
func (*CoordinateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afe31759757e49a, []int{2}
}

func (m *CoordinateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinateReq.Unmarshal(m, b)
}
func (m *CoordinateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinateReq.Marshal(b, m, deterministic)
}
func (m *CoordinateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinateReq.Merge(m, src)
}
func (m *CoordinateReq) XXX_Size() int {
	return xxx_messageInfo_CoordinateReq.Size(m)
}
func (m *CoordinateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinateReq proto.InternalMessageInfo

func (m *CoordinateReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CoordinateReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *CoordinateReq) GetJobIds() []string {
	if m != nil {
		return m.JobIds
	}
	return nil
}

func (m *CoordinateReq) GetCtrIds() []string {
	if m != nil {
		return m.CtrIds
	}
	return nil
}

func (m *CoordinateReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

// Generic response
type Response struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afe31759757e49a, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Response) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerInfo)(nil), "ContainerInfo")
	proto.RegisterType((*SyncDataReq)(nil), "SyncDataReq")
	proto.RegisterType((*CoordinateReq)(nil), "CoordinateReq")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("container.proto", fileDescriptor_7afe31759757e49a)
}

var fileDescriptor_7afe31759757e49a = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x65, 0xda, 0x26, 0xcd, 0xf4, 0x0f, 0xc8, 0x88, 0xdd, 0x68, 0x39, 0x50, 0x0a, 0x88,
	0x9c, 0x22, 0xb4, 0x70, 0xe3, 0x56, 0xb8, 0x44, 0xe2, 0x80, 0x5c, 0x4e, 0x5c, 0x22, 0xc7, 0x1e,
	0x58, 0x57, 0x5b, 0x3b, 0xd8, 0xee, 0x4a, 0x79, 0x01, 0x78, 0x03, 0x9e, 0x91, 0xc7, 0x40, 0x71,
	0xda, 0x34, 0x20, 0x2e, 0x9c, 0xe2, 0xf9, 0xe6, 0x73, 0x66, 0xbe, 0x9f, 0x0c, 0xf7, 0x85, 0xd1,
	0x9e, 0x2b, 0x8d, 0x36, 0xaf, 0xad, 0xf1, 0x66, 0xfd, 0x8b, 0xc0, 0xe2, 0xdd, 0x49, 0x2b, 0xf4,
	0x17, 0x43, 0x9f, 0xc2, 0xbc, 0x37, 0x95, 0x4a, 0xa6, 0x64, 0x45, 0xb2, 0x84, 0xcd, 0x7a, 0xad,
	0x90, 0xf4, 0x02, 0x22, 0xe7, 0xb9, 0x3f, 0xb8, 0xf4, 0x5e, 0x68, 0x1e, 0x2b, 0x7a, 0x09, 0x71,
	0x7d, 0xd3, 0x94, 0x4a, 0xba, 0x74, 0xb4, 0x1a, 0x65, 0x13, 0x16, 0xd5, 0x37, 0x4d, 0x21, 0x1d,
	0x7d, 0x04, 0xd1, 0xce, 0x54, 0xed, 0xdf, 0xc6, 0xe1, 0xc2, 0x64, 0x67, 0xaa, 0x42, 0xd2, 0x27,
	0x30, 0x6b, 0x65, 0x8b, 0xf5, 0xad, 0x12, 0x3c, 0x9d, 0xac, 0x48, 0x36, 0x61, 0xb0, 0x33, 0x15,
	0xeb, 0x14, 0xfa, 0x02, 0x96, 0xa8, 0x79, 0x75, 0x8b, 0xa5, 0x45, 0x61, 0xee, 0xd0, 0xa6, 0xd1,
	0x8a, 0x64, 0x53, 0xb6, 0xe8, 0x54, 0xd6, 0x89, 0xf4, 0x39, 0x2c, 0x6b, 0x7e, 0x70, 0x28, 0xcb,
	0xaa, 0x29, 0x6b, 0x44, 0x9b, 0xc6, 0x61, 0xcc, 0xbc, 0x53, 0x37, 0xcd, 0x47, 0x44, 0xbb, 0xfe,
	0x41, 0x60, 0xb6, 0x6d, 0xb4, 0x78, 0xcf, 0x3d, 0x67, 0xf8, 0x8d, 0x52, 0x18, 0x1f, 0x0e, 0x7d,
	0xc0, 0x70, 0x6e, 0x13, 0x68, 0x23, 0xb1, 0xdd, 0xf4, 0x18, 0xad, 0x2d, 0x0b, 0x49, 0x73, 0x80,
	0x9e, 0x40, 0x97, 0x6e, 0x76, 0xbd, 0xcc, 0xff, 0x20, 0xc7, 0x06, 0x0e, 0xfa, 0x18, 0x12, 0xd7,
	0x68, 0x51, 0x7a, 0xb5, 0xc7, 0x10, 0x7a, 0xc4, 0xa6, 0xad, 0xf0, 0x49, 0xed, 0x71, 0xfd, 0x3d,
	0x40, 0x37, 0x56, 0x2a, 0xcd, 0x3d, 0xfe, 0xf7, 0x2e, 0x97, 0x10, 0x77, 0x34, 0xbb, 0x45, 0x12,
	0x16, 0x05, 0x9c, 0x81, 0xbf, 0xf0, 0x36, 0x34, 0xc6, 0x5d, 0x43, 0x78, 0xdb, 0x36, 0x2e, 0x20,
	0xe2, 0xc2, 0x2b, 0xa3, 0x03, 0xe3, 0x84, 0x1d, 0xab, 0xf5, 0x07, 0x98, 0x32, 0x74, 0xb5, 0xd1,
	0x0e, 0xff, 0xb9, 0x02, 0x85, 0xb1, 0x30, 0x12, 0xc3, 0xfc, 0x05, 0x0b, 0x67, 0x9a, 0x42, 0xbc,
	0x47, 0xe7, 0xf8, 0x57, 0x4c, 0x47, 0xc1, 0x7a, 0x2a, 0xaf, 0x7f, 0x12, 0x78, 0xd0, 0x13, 0xd9,
	0xa2, 0xbd, 0x53, 0x02, 0xe9, 0x33, 0x98, 0x9e, 0xa0, 0xd3, 0x79, 0x3e, 0xe0, 0x7f, 0x95, 0xe4,
	0xfd, 0xec, 0x97, 0x00, 0x67, 0x1e, 0xb4, 0xe5, 0x3a, 0x80, 0x33, 0x34, 0xbe, 0x81, 0x87, 0x85,
	0x56, 0x7e, 0x63, 0x0d, 0x97, 0x82, 0x3b, 0xbf, 0xf5, 0x16, 0xf9, 0x9e, 0x9e, 0x1d, 0x57, 0x7f,
	0x5d, 0xce, 0xc8, 0x2b, 0xb2, 0x49, 0x3e, 0xc7, 0xf9, 0xdb, 0xf0, 0xde, 0xab, 0x28, 0x7c, 0x5e,
	0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15, 0x3b, 0x8e, 0x92, 0x09, 0x03, 0x00, 0x00,
}
