FROM ubuntu:22.04 AS build

ARG VERSION=26.1.0
ARG TARGETPLATFORM

RUN apt update && apt install -y wget unzip &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    rm -rf /var/tmp/* &&\
    rm -rf /tmp/* &&\
    ARCH=$(case "${TARGETPLATFORM}" in \
        "linux/amd64") echo "x86_64" ;; \
        "linux/arm64") echo "aarch64" ;; \
        *) echo "Unsupported TARGETPLATFORM: ${TARGETPLATFORM}" && exit 1 ;; \
    esac) &&\
    wget https://gitcode.com/ascend/mind-cluster/releases/download/v${VERSION}/Ascend-mindxdl-k8s-rdma-shared-dev-plugin_${VERSION}_linux-${ARCH}.zip &&\
    unzip Ascend-mindxdl-k8s-rdma-shared-dev-plugin_${VERSION}_linux-${ARCH}.zip -d /build

FROM ubuntu:22.04

RUN usermod root -s /usr/sbin/nologin

COPY --from=build /build/k8s-rdma-shared-dp /usr/local/bin/k8s-rdma-shared-dp
COPY --from=build /build/agreement.txt /usr/local/
COPY --from=build /build/fault_code.json /etc/rdma-plugin/
COPY --from=build /build/fault_detection.sh /etc/rdma-plugin/

RUN chmod 550 /usr/local/bin/k8s-rdma-shared-dp &&\
    chmod 440 /usr/local/agreement.txt &&\
    chmod 550 /etc/rdma-plugin/fault_detection.sh &&\
    sed -i 's/\r$//' /etc/rdma-plugin/fault_detection.sh &&\
    echo 'umask 027' >> /etc/profile &&\
    echo 'source /etc/profile' >> ~/.bashrc

WORKDIR /etc/rdma-plugin

LABEL io.k8s.display-name="RDMA Shared Device Plugin"

ENTRYPOINT ["/bin/bash", "-c", "cat /usr/local/agreement.txt; exec /usr/local/bin/k8s-rdma-shared-dp"]
