FROM openeuler/openeuler:24.03-lts AS build

ARG VERSION=26.1.0
ARG TARGETPLATFORM

RUN yum update -y && \
    yum install -y wget unzip && \
    yum clean all && rm -rf /var/cache/yum /tmp/* && \
    mkdir -p /build && rm -rf /build/* && \
    ARCH=$(case "${TARGETPLATFORM}" in \
        "linux/amd64") echo "x86_64" ;; \
        "linux/arm64") echo "aarch64" ;; \
        *) echo "Unsupported TARGETPLATFORM: ${TARGETPLATFORM}" && exit 1 ;; \
    esac) && \
    wget https://gitcode.com/ascend/mind-cluster/releases/download/v${VERSION}/Ascend-mindxdl-npu-exporter_${VERSION}_linux-${ARCH}.zip && \
    unzip Ascend-mindxdl-npu-exporter_${VERSION}_linux-${ARCH}.zip -d /build && \
    wget https://mirrors.huaweicloud.com/ascend/archive/rpm/unifiedbus/common/umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz  --no-check-certificate  && \
    cp umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz /build

FROM openeuler/openeuler:24.03-lts

ARG TARGETPLATFORM
ARG UMDK_PKG=umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz

COPY --from=build /build/${UMDK_PKG} /tmp/${UMDK_PKG}

RUN yum install -y shadow-utils libnl3 libnl3-devel && \
    yum clean all && rm -rf /var/cache/yum && \
    if [ "${TARGETPLATFORM}" = "linux/arm64" ] && [ -n "${UMDK_PKG}" ] && [ -f "/tmp/${UMDK_PKG}" ]; then \
        echo "INFO: Install umdk from /tmp/${UMDK_PKG}"; \
        mkdir -p /tmp/umdk_pkgs; \
        tar -mzxf "/tmp/${UMDK_PKG}" -C /tmp/umdk_pkgs; \
        rpm -ivh /tmp/umdk_pkgs/*.rpm; \
    elif [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
        echo "INFO: amd64 platform skip local umdk rpm install"; \
    else \
        echo "WARN: umdk package not supported in platform ${TARGETPLATFORM}"; \
    fi && \
    rm -rf /tmp/* && \
    useradd -d /home/HwHiAiUser -u 1000 -m -s /usr/sbin/nologin HwHiAiUser &&\
    usermod root -s /usr/sbin/nologin

COPY --from=build /build/npu-exporter /usr/local/bin/npu-exporter
COPY --from=build /build/run_for_310P_1usoc.sh /
COPY --from=build /build/agreement.txt /usr/local/
COPY --from=build /build/metricConfiguration.json /build/pluginConfiguration.json /user/mind-cluster/npu-exporter-config/

RUN chown root:root /usr/local/bin/npu-exporter &&\
    chmod 750 -R /home/HwHiAiUser &&\
    chmod 500 /run_for_310P_1usoc.sh &&\
    chmod 550 /usr/local/bin/ &&\
    chmod 500 /usr/local/bin/npu-exporter &&\
    chmod 440 /user/mind-cluster/npu-exporter-config/metricConfiguration.json &&\
    chmod 440 /user/mind-cluster/npu-exporter-config/pluginConfiguration.json &&\
    chmod 440 /usr/local/agreement.txt &&\
    echo 'umask 027' >> /etc/profile && \
    echo 'source /etc/profile' >> ~/.bashrc

ENV LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/add-ons:/usr/local/Ascend/driver/lib64:/usr/local/dcmi

ENTRYPOINT ["/bin/bash", "-c", "cat /usr/local/agreement.txt; exec /bin/bash"]
