FROM openeuler/openeuler:24.03-lts AS build

ARG VERSION=26.1.1
ARG TARGETPLATFORM

RUN yum update -y && \
    yum install -y wget unzip && \
    yum clean all && rm -rf /var/cache/yum /tmp/* && \
    mkdir -p /build && rm -rf /build/* && \
    ARCH=$(case "${TARGETPLATFORM}" in \
        "linux/amd64") echo "x86_64" ;; \
        "linux/arm64") echo "aarch64" ;; \
        *) echo "Unsupported TARGETPLATFORM: ${TARGETPLATFORM}" && exit 1 ;; \
    esac) && \
    wget https://gitcode.com/ascend/mind-cluster/releases/download/v${VERSION}/Ascend-mindxdl-device-plugin_${VERSION}_linux-${ARCH}.zip && \
    unzip -o Ascend-mindxdl-device-plugin_${VERSION}_linux-${ARCH}.zip -d /build && \
    wget https://mirrors.huaweicloud.com/ascend/archive/rpm/unifiedbus/common/umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz && \
    cp umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz /build

FROM openeuler/openeuler:24.03-lts

ARG TARGETPLATFORM
ARG UMDK_PKG=umdk-urma-26.06.0-B016.glibc217.aarch64.rpm.tar.gz

COPY --from=build /build/${UMDK_PKG} /tmp/${UMDK_PKG}

RUN yum install -y shadow-utils libnl3 libnl3-devel ca-certificates bash glibc sqlite-devel gcc gcc-c++ make cmake git  jq curl numactl-devel && \
    yum clean all && rm -rf /var/cache/yum && \
    if [ "${TARGETPLATFORM}" = "linux/arm64" ] && [ -n "${UMDK_PKG}" ] && [ -f "/tmp/${UMDK_PKG}" ]; then \
        echo "INFO: Install umdk from /tmp/${UMDK_PKG}"; \
        mkdir -p /tmp/umdk_pkgs; \
        tar -mzxf "/tmp/${UMDK_PKG}" -C /tmp/umdk_pkgs; \
        rpm -ivh /tmp/umdk_pkgs/*.rpm; \
    elif [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
        echo "INFO: amd64 platform skip local umdk rpm install"; \
    else \
        echo "WARN: umdk package not supported in platform ${TARGETPLATFORM}"; \
    fi && \
    rm -rf /tmp/* && \
    groupadd -g 1000 HwHiAiUser && useradd -u 1000 -g HwHiAiUser -d /home/HwHiAiUser -m HwHiAiUser && \
    groupadd -g 1101 HwDmUser && useradd -u 1101 -g HwDmUser -d /home/HwDmUser -m HwDmUser && \
    groupadd -g 1102 HwBaseUser && useradd -u 1102 -g HwBaseUser -d /home/HwBaseUser -m HwBaseUser && \
    usermod -aG HwBaseUser HwHiAiUser && \
    usermod -aG HwDmUser HwHiAiUser && \
    usermod -aG HwBaseUser HwDmUser && \
    usermod -aG HwHiAiUser HwDmUser && \
    usermod root -s /bin/false

ENV LD_LIBRARY_PATH /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common

COPY --from=build /build/device-plugin /usr/local/bin/
COPY --from=build /build/run_for_310P_1usoc.sh /
COPY --from=build /build/faultCode.json /usr/local/
COPY --from=build /build/faultCustomization.json /usr/local/
COPY --from=build /build/SwitchFaultCode.json /usr/local/
COPY --from=build /build/deviceNameCustomization.json /usr/local/
COPY --from=build /build/hangDetectionConfig.json /usr/local/
COPY --from=build /build/hotResetPluginConfiguration.json /usr/local/
COPY --from=build /build/agreement.txt /usr/local/
COPY --from=build /build/npu-nic-mapping.json /user/mindx-dl/npu/

RUN chmod 550 /usr/local/bin/device-plugin && \
    chmod 550 /usr/local/bin && \
    chmod 440 /usr/local/faultCode.json && \
    chmod 440 /usr/local/faultCustomization.json && \
    chmod 440 /usr/local/SwitchFaultCode.json && \
    chmod 440 /usr/local/deviceNameCustomization.json && \
    chmod 440 /usr/local/hangDetectionConfig.json && \
    chmod 440 /usr/local/hotResetPluginConfiguration.json && \
    chmod 440 /user/mindx-dl/npu/npu-nic-mapping.json &&\
    chmod 440 /usr/local/agreement.txt && \
    chmod 750 /home/HwHiAiUser && \
    chmod 500 /run_for_310P_1usoc.sh && \
    echo 'umask 027' >> /etc/profile && \
    echo 'source /etc/profile' >> ~/.bashrc

ENTRYPOINT ["/bin/bash", "-c", "cat /usr/local/agreement.txt; exec /bin/bash"]
