apiVersion: v1
kind: Namespace
metadata:
  name: mindx-dl
  annotations:
    helm.sh/resource-policy: keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-system
  annotations:
    helm.sh/resource-policy: keep
