{{- $filePath := "yamls/default/**.yaml" -}}

{{- $files := .Files.Glob $filePath -}}
{{- if not $files -}}
  {{- fail (printf "No files found matching pattern: %s" $filePath) -}}
{{- end -}}

{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob $filePath }}
  {{- with $currentScope }}
    {{- $content := $.Files.Get $path -}}
    {{- tpl $content $ }}
---
  {{- end }}
{{- end }}
