FROM alpine:latest AS build

ARG VERSION=26.1.0
ARG TARGETPLATFORM

RUN apk update && apk add --no-cache \
    wget \
    unzip \
    ca-certificates \
    libc6-compat

RUN ARCH=$(case "${TARGETPLATFORM}" in \
        "linux/amd64") echo "x86_64" ;; \
        "linux/arm64") echo "aarch64" ;; \
        *) echo "Unsupported TARGETPLATFORM: ${TARGETPLATFORM}" && exit 1 ;; \
    esac) &&\
    wget https://gitcode.com/ascend/mind-cluster/releases/download/v${VERSION}/Ascend-mindxdl-volcano_${VERSION}_linux-${ARCH}.zip &&\
    unzip Ascend-mindxdl-volcano_${VERSION}_linux-${ARCH}.zip -d /build

FROM alpine:latest

COPY --from=build /build/volcano-v1.9.0/vc-controller-manager /vc-controller-manager
COPY --from=build /build/volcano-v1.9.0/agreement.txt /usr/local/

RUN adduser -h /home/hwMindX -u 9000 -D -s /sbin/nologin hwMindX &&\
    sed '1c root:x:0:0:root:/root:/sbin/nologin' /etc/passwd &&\
    chown -R hwMindX:hwMindX vc-controller-manager /usr/local/agreement.txt &&\
    chmod 750 /home/hwMindX &&\
    chmod 500 vc-controller-manager &&\
    chmod 440 /usr/local/agreement.txt

USER hwMindX

ENTRYPOINT ["/bin/sh", "-c", "cat /usr/local/agreement.txt; exec /bin/sh"]
