# User-configurable parameters
is310P1usoc: false
volcanoType: true
image:
  repository: ""
  tag: ""
  pullPolicy: ""
resources:
  requests:
    memory: ""
    cpu: ""
  limits:
    memory: ""
    cpu: ""

args: ""
command: ""

# Built-in parameters
