FROM alpine:latest

COPY vc-controller-manager /vc-controller-manager
RUN mkdir -p /lib64 && \
    if [ "$(uname -m)" = "x86_64" ]; then \
        ln -s /lib/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2; \
    elif [ "$(uname -m)" = "aarch64" ]; then \
        ln -s /lib/ld-musl-aarch64.so.1 /lib/ld-linux-aarch64.so.1; \
    fi

RUN adduser -h /home/hwMindX -u 9000 -D -s /sbin/nologin hwMindX && \
    sed '1c root:x:0:0:root:/root:/sbin/nologin' /etc/passwd && \
    chown -R hwMindX:hwMindX vc-controller-manager && \
    chmod 750 /home/hwMindX && \
    chmod 500 vc-controller-manager
USER hwMindX
